<?php

/***************** DO NOT EDIT THIS FILE *************************
******************************************************************

INFORMATION:
------------

This is a core theme file, you should not need to edit 
this file directly. Code changes maybe lost during updates.

LAST UPDATED: 27th March 2011
EDITED BY: MARK FAIL
------------------------------------------------------------------

******************************************************************/

if(isset($_GET['cid']) && is_numeric($_GET['cid']) ){

	$te = explode("themes",$_SERVER['SCRIPT_FILENAME']);
	$tf = explode("PPT",trim($te[1])); 
	$themeName = str_replace("\\","",str_replace("\\\\","",str_replace("/","",str_replace("////","",$tf[0]))));	
	$path=dirname(realpath($_SERVER['SCRIPT_FILENAME']));
	$path_parts = pathinfo($path);
	$p = str_replace("wp-content","",$path_parts['dirname']);	
	$p = str_replace("themes","",$p);
	$p = str_replace("PPT","",$p);
	$p = str_replace($themeName,"",$p);
	$p = str_replace("template_","",$p);
	$p = str_replace("\\\\","",$p);
	$p = str_replace("////","",$p);
 			
	require( $p.'/wp-config.php' );
	
	$GLOBALS['premiumpress']['language'] = get_option("language");
	$PPT->Language();

	$the_post = get_post($_GET['cid']);
 	$expires = get_post_meta($the_post->ID, "expires", true);
	$code = get_post_meta($the_post->ID, "code", true);
	$url = get_post_meta($the_post->ID, "url", true);
	if($url == ""){  }else{ $imgT = "url"; } $imgT = "full";
?>
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html>
<head>
<title><?php echo $the_post->post_title; ?></title>
<meta http-equiv="Content-type" content="text/html; charset=UTF-8" /> 
<META NAME="ROBOTS" CONTENT="NOINDEX, FOLLOW">
<META NAME="ROBOTS" CONTENT="INDEX, NOFOLLOW">
<META NAME="ROBOTS" CONTENT="NOINDEX, NOFOLLOW">
<style>
body { font-size:15px; valign:top;}
h1 { padding:0px; margin-top:0px;}
._print { padding:10px;  border:2px dashed #000; }
.printbutton { padding:10px; font-size:16px; background: #efefef; border:1px solid #ddd; }
.printbutton:hover { background:#666; }
.printbutton a { font-size:18px; text-decoration:none; color:#333333; }
.printbutton a:hover { color:#FFFFFF;  font-weight:bold; }
</style>
</head>

<body>
<div style="border:1px solid #000; margin:20px; padding:10px">
<div class="_print"> 

<h1><?php echo $the_post->post_title; ?></h1>
<?php if($the_post->post_content =="" || $the_post->post_content != $the_post->post_excerpt){ ?> <p><?php echo $the_post->post_excerpt; ?></p><?php } ?>
<p><?php echo $the_post->post_content; ?></p>
<?php if($expires !=""){ ?><p><strong>Expires: <?php echo $expires; ?> </strong></p><?php } ?>  
<?php if($code !=""){ ?><p><strong>Coupon Code: <?php echo $code; ?> </strong></p><?php } ?> 
<center><img src="<?php echo $PPT->Image($the_post->ID,$imgT); ?>" alt="<?php the_title(); ?>" style="max-width:580px;"/></center>


<div style="clear:both;"></div> 
</div></div>

<center><div  class="printbutton"><a href="javascript:void(0);" onClick="window.print()"><?php echo SPEC($GLOBALS['_LANG']['_printpage']); ?></a></div></center>
</body>
</html>
<?php } ?>
