<?php

/***************** DO NOT EDIT THIS FILE *************************
******************************************************************

INFORMATION:
------------

This is a core theme file, you should not need to edit 
this file directly. Code changes maybe lost during updates.

LAST UPDATED: June 26th 2011
EDITED BY: MARK FAIL
------------------------------------------------------------------

******************************************************************/

/* ================ LOAD TEMPLATE FILE =========================== */
global $PPT, $wp_query, $PPTDesign, $ThemeDesign,$PPTFunction,$current_user; get_currentuserinfo();
 
 
$curauth = $wp_query->get_queried_object();
include("template_".strtolower(PREMIUMPRESS_SYSTEM)."/_author.php");

?>