<?php

/***************** DO NOT EDIT THIS FILE *************************
******************************************************************

INFORMATION:
------------

This is a core theme file, you should not need to edit 
this file directly. Code changes maybe lost during updates.

LAST UPDATED: June 26th 2011
EDITED BY: MARK FAIL
------------------------------------------------------------------

******************************************************************/
 
/* ================ LOAD TEMPLATE FILE =========================== */	
 
if(file_exists(str_replace("functions/","",THEME_PATH)."/themes/".get_option('theme')."/_comments.php")){
		
		include(str_replace("functions/","",THEME_PATH)."/themes/".get_option('theme').'/_comments.php');
		
}else{ 
	
		include("template_".strtolower(PREMIUMPRESS_SYSTEM)."/_comments.php");
	
}
?>