<?php

/***************** DO NOT EDIT THIS FILE *************************
******************************************************************

INFORMATION:
------------

This is a core theme file, you should not need to edit 
this file directly. Code changes maybe lost during updates.

LAST UPDATED: 29th March 2011
EDITED BY: MARK FAIL
------------------------------------------------------------------

******************************************************************/

global $PPT,$ThemeDesign, $PPTDesign, $user_ID, $userdata; get_currentuserinfo();

 /* ================ LOAD TEMPLATE FILE =========================== */

if(file_exists(str_replace("functions/","",THEME_PATH)."/themes/".$GLOBALS['premiumpress']['theme']."/_sidebar.php")){
		
	include(str_replace("functions/","",THEME_PATH)."/themes/".$GLOBALS['premiumpress']['theme'].'/_sidebar.php');
		
}else{ 
	
	include("template_".strtolower(PREMIUMPRESS_SYSTEM)."/_sidebar.php");
	
}

?>