<?php

/***************** DO NOT EDIT THIS FILE *************************
******************************************************************

INFORMATION:
------------

This is a core theme file, you should not need to edit 
this file directly. Code changes maybe lost during updates.

LAST UPDATED: June 26th 2011
EDITED BY: MARK FAIL
------------------------------------------------------------------

******************************************************************/

global $ThemeDesign, $current_user; get_currentuserinfo();

// CHECK AND UPDATE THE HIT COUNTER
$PPT->UpdateHits($post->ID,get_post_meta($post->ID, "hits", true));

// CHECK IF THE LISTING HAS EXPIRED
$PPT->CheckExpired($post->ID,$post->post_date);			
			
// CHECK IF THE LISTING NEEDS PRUNING
$PPT->CheckPrune($post);

// GET THE LISTING PACKAGE DATA
if(strtolower(PREMIUMPRESS_SYSTEM) != "shopperpress"){
	$GLOBALS['packageID'] 		= get_post_meta($post->ID, "packageID", true);
	if(strlen($GLOBALS['packageID']) > 0){
		$packdata = get_option("packages");
		$GLOBALS['packageName'] = $packdata[$GLOBALS['packageID']]['name'];
		$GLOBALS['packageIcon'] = $packdata[$GLOBALS['packageID']]['icon'];
	 
	}
}

if($post->post_type !="post"){ // LOAD THE ARTICLE PAGE INSTEAD IF THIS IS AN ARTICLE

	$GLOBALS['ARTICLEPAGE'] = 1;;

	if(file_exists(str_replace("functions/","",THEME_PATH)."/themes/".get_option('theme')."/_articlepage.php")){
			
		include(str_replace("functions/","",THEME_PATH)."/themes/".get_option('theme').'/_articlepage.php');
			
	}else{ 
		
		include("template_".strtolower(PREMIUMPRESS_SYSTEM)."/_articlepage.php");
		
	} 
	
}else{

	if(file_exists(str_replace("functions/","",THEME_PATH)."/themes/".get_option('theme')."/_single.php")){
			
		include(str_replace("functions/","",THEME_PATH)."/themes/".get_option('theme').'/_single.php');
			
	}else{ 
 
		include("template_".strtolower(PREMIUMPRESS_SYSTEM)."/_single.php");
		
	} 

} 

 ?>