<?php
/*
Template Name: [Payment Template]
*/

/***************** DO NOT EDIT THIS FILE *************************
******************************************************************

INFORMATION:
------------

This is a core theme file, you should not need to edit 
this file directly. Code changes maybe lost during updates.

LAST UPDATED: June 26th 2011
EDITED BY: MARK FAIL
------------------------------------------------------------------

******************************************************************/

global $PPTFunction, $userdata; get_currentuserinfo(); // grabs the user info and puts into vars

$wpdb->hide_errors(); $PPTFunction->auth_redirect_login(); nocache_headers();
 
	/* ================ LOAD TEMPLATE FILE =========================== */	
 
	if(file_exists(str_replace("functions/","",THEME_PATH)."/themes/".get_option('theme')."/_tpl_payments.php")){
		
		include(str_replace("functions/","",THEME_PATH)."/themes/".get_option('theme').'/_tpl_payments.php');
		
	}else{ 
	
		include("template_".strtolower(PREMIUMPRESS_SYSTEM)."/_tpl_payments.php");
	
	}
?>