<?php
/*
Template Name: [Contact Template]
*/

/***************** DO NOT EDIT THIS FILE *************************
******************************************************************

INFORMATION:
------------

This is a core theme file, you should not need to edit 
this file directly. Code changes maybe lost during updates.

LAST UPDATED: June 26th 2011
EDITED BY: MARK FAIL
------------------------------------------------------------------

******************************************************************/

global $PPTFunction, $userdata; get_currentuserinfo(); // grabs the user info and puts into vars

$wpdb->hide_errors(); nocache_headers();

$email_nr1 = rand("0", "9");$email_nr2 = rand("0", "9");
/* =========================================== */

if(isset($_POST['action'])){ $_GET['action'] = $_POST['action']; }
if(isset($_GET['action']) && isset($_POST['form']['code']) ){ 

		$GLOBALS['premiumpress']['language'] = get_option("language");
		$PPT->Language();
 
		//check_admin_referer('ContactForm');	
		
		if(	isset($_POST['form']['code']) && $_POST['form']['code'] == $_POST['form']['code_value']){
		
		
			$message = "<p> Name : " . strip_tags($_POST['form']['name']) . "
						<p> Email : " . strip_tags($_POST['form']['email']) . "
						<p> Message : " . strip_tags($_POST['form']['message']) . "";
						
			if(isset($_POST['report']) && is_numeric($_POST['report']) ){
			
			$message .= "<p> Reported post ID:  ".strip_tags($_POST['report'])."  <a href='" .get_permalink($_POST['report']) ."'>click here to view this post</a></p>";
			
			}
		
			// SEND EMAIL
			$emailID = get_option("email_admin_contact");
			if($emailID != "0" && strlen($emailID) > 0 ){					 
			SendMemberEmail("admin", $emailID,$message);
			}
			 
		
		$GLOBALS['error'] 		= 1;
		$GLOBALS['error_type'] 	= "success"; //ok,warn,error,info
		$GLOBALS['error_msg'] 	= SPEC($GLOBALS['_LANG']['_tpl_contact_error1']);
				
		}else{

		$GLOBALS['error'] 		= 1;
		$GLOBALS['error_type'] 	= "error"; //ok,warn,error,info
		$GLOBALS['error_msg'] 	= SPEC($GLOBALS['_LANG']['_tpl_contact_error2']);		
		
		}

 
}

function NoFollowIndex(){

echo '<META NAME="ROBOTS" CONTENT="NOINDEX, FOLLOW"><META NAME="ROBOTS" CONTENT="INDEX, NOFOLLOW"><META NAME="ROBOTS" CONTENT="NOINDEX, NOFOLLOW">';

}

// no index for report page
if(isset($_GET['report'])){
add_filter('wp_head','NoFollowIndex');
}

/* =================== START DISPLAY ================== */
 

if(file_exists(str_replace("functions/","",THEME_PATH)."/themes/".get_option('theme')."/_tpl_contact.php")){
		
	include(str_replace("functions/","",THEME_PATH)."/themes/".get_option('theme').'/_tpl_contact.php');
		
}else{ 
	
	include("template_".strtolower(PREMIUMPRESS_SYSTEM)."/_tpl_contact.php");
	
}
?>

