<?php
/*
Template Name: [Edit/Manage Template]
*/

/***************** DO NOT EDIT THIS FILE *************************
******************************************************************

INFORMATION:
------------

This is a core theme file, you should not need to edit 
this file directly. Code changes maybe lost during updates.

LAST UPDATED: June 26th 2011
EDITED BY: MARK FAIL
------------------------------------------------------------------

******************************************************************/

global $PPT, $PPTFunction, $userdata; get_currentuserinfo(); // grabs the user info and puts into vars

$wpdb->hide_errors(); nocache_headers(); $PPTFunction->auth_redirect_login();

/* ============================= PREMIUM PRESS FOR SUBMISSION ========================================= */

$GLOBALS['premiumpress']['language'] = get_option("language");
$PPT->Language();

if(isset($_GET['eid']) && isset($_GET['dd']) && is_numeric($_GET['eid']) ){
 
	$data = $PPT->Deletelisting($user_ID, $_GET['eid']);

	$GLOBALS['error'] 		= 1;
	$GLOBALS['error_type'] 	= "success"; 
	$GLOBALS['error_msg'] 	= SPEC($GLOBALS['_LANG']['_tpl_edit_error1']);	
}

if(isset($_POST['action'])){

	if($_POST['action'] == "addfeedback"){
	
		// GET THE AUTHOR ID FOR SAVING
		$result = mysql_query("SELECT post_author FROM ".$wpdb->prefix."posts WHERE ".$wpdb->prefix."posts.ID='".strip_tags(PPTCLEAN($_POST['auctionID']))."' LIMIT 1", $wpdb->dbh) or die(mysql_error().' on line: '.__LINE__);							
		$array = mysql_fetch_assoc($result);			 
		 
	 
		$my_post = array();
		$my_post['post_title'] 		= "Feedback for ".$_POST['auctionID'];
		$my_post['post_content'] 	= strip_tags(strip_tags($_POST['message_message']));
		$my_post['post_excerpt'] 	= "";
		$my_post['post_status'] 	= "publish";
		$my_post['post_type'] 		= "ppt_feedback";
		$my_post['post_author'] 	= $userdata->ID;
		$POSTID 					= wp_insert_post( $my_post );
		
		add_post_meta($POSTID, "feedback_authorID", $userdata->ID);	
		add_post_meta($POSTID, "feedback_postID", $_POST['auctionID']);	
		add_post_meta($POSTID, "feedback_forID", $array['post_author']);
		
		add_post_meta($POSTID, "completed", $_POST['completed']);
		add_post_meta($POSTID, "rating", $_POST['rating']);
		
		// UPDATE THE POST STATUS TO FINISHED
		update_post_meta($_POST['auctionID'], "bid_status", "finished");
		
		// UPDATE THE USERS ACCOUNT AND GIVE THEM THE FEEDBACK + MONEY EARNED
		
		/*Load current data*/
		$cuserdata = get_userdata($array['post_author']);
		$_POST['userdata']['ID']  = $array['post_author'];
		$_POST['userdata']['yim']['feedback_rating'] = $cuserdata->yim['feedback_rating'] + $_POST['rating'];
		$_POST['userdata']['yim']['feedback_rating_total'] = $cuserdata->yim['feedback_rating_total'] + 5;
		$_POST['userdata']['yim']['feedback_earnings'] = $cuserdata->yim['feedback_earnings'] + get_post_meta($_POST['auctionID'], "SelectBidPrice", true);
		wp_update_user( $_POST['userdata'] );
	
	
		$GLOBALS['error'] 		= 1;
		$GLOBALS['error_type'] 	= "success"; //ok,warn,error,info
		$GLOBALS['error_msg'] 	= SPEC($GLOBALS['_LANG']['_tpl_edit_error2']);
		
		// SEND EMAIL
		//$emailID = get_option("email_message_new");					 
		//if(is_numeric($emailID) && $emailID != 0){
		//	SendMemberEmail($userdata, $emailID);
		//}
		
	}elseif($_POST['action'] == "deletefeedback"){
	
 
	
	}	

}


if(isset($_GET['eid']) && isset($_GET['dd']) && is_numeric($_GET['eid']) ){
 
	$data = $PPT->Deletelisting($user_ID, $_GET['eid']);

	$GLOBALS['error'] 		= 1;
	$GLOBALS['error_type'] 	= "success"; //ok,warn,error,info
	$GLOBALS['error_msg'] 	= SPEC($GLOBALS['_LANG']['_tpl_edit_error3']);
	
}

 
/* =================== START DISPLAY ================== */

if(file_exists(str_replace("functions/","",THEME_PATH)."/themes/".get_option('theme')."/_tpl_edit.php")){
		
	include(str_replace("functions/","",THEME_PATH)."/themes/".get_option('theme').'/_tpl_edit.php');
		
}else{ 
	
	include("template_".strtolower(PREMIUMPRESS_SYSTEM)."/_tpl_edit.php");
	
}
 
?>