<?php
/*
Template Name: [Messages Template]
*/
 
/***************** DO NOT EDIT THIS FILE *************************
******************************************************************

INFORMATION:
------------

This is a core theme file, you should not need to edit 
this file directly. Code changes maybe lost during updates.

LAST UPDATED: June 26th 2011
EDITED BY: MARK FAIL
------------------------------------------------------------------

******************************************************************/

global $PPTFunction, $userdata; get_currentuserinfo(); // grabs the user info and puts into vars

$wpdb->hide_errors(); nocache_headers(); $PPTFunction->auth_redirect_login();


if(isset($_POST['action'])){

	$GLOBALS['premiumpress']['language'] = get_option("language");
	$PPT->Language();

	if($_POST['action'] == "add"){
	
	$dd = get_userdatabylogin( $_POST['message_name'] );
	
	if(isset($dd->ID)){
	
		// CHECK HOW MANY MESSAGES HAVE BEEN SENT ALREADY FROM THIS USER
		$SQL = "SELECT count(*) AS total FROM $wpdb->posts WHERE post_type = 'ppt_message' AND post_author = '".$userdata->ID."' AND post_date LIKE ('".date("Y-m-d")."%')";	
		$found = (array)$wpdb->get_results($SQL);
 
		if($found[0]->total < 5){
	 
			$my_post = array();
			$my_post['post_title'] 		= strip_tags(strip_tags($_POST['message_subject']));
			$my_post['post_content'] 	= strip_tags(strip_tags($_POST['message_message']));
			$my_post['post_excerpt'] 	= "";
			$my_post['post_status'] 	= "publish";
			$my_post['post_type'] 		= "ppt_message";
			$my_post['post_author'] 	= $userdata->ID;
			$POSTID 					= wp_insert_post( $my_post );
			add_post_meta($POSTID, "username", $_POST['message_name']);	
			add_post_meta($POSTID, "userID", $dd->ID);
		
			$GLOBALS['error'] 		= 1;
			$GLOBALS['error_type'] 	= "success"; //ok,warn,error,info
			$GLOBALS['error_msg'] 	= SPEC($GLOBALS['_LANG']['_tpl_messages_error1']);
			
			// SEND EMAIL
			$emailID = get_option("email_message_new");					 
			if(is_numeric($emailID) && $emailID != 0){
				SendMemberEmail($dd->ID, $emailID);
			}
			
		}else{
		
		$GLOBALS['error'] 		= 1;
		$GLOBALS['error_type'] 	= "error"; //ok,warn,error,info
		$GLOBALS['error_msg'] 	= "You have reached your daily limit of 5 messages per day."; 
		
		
		}
		
	}else{
	
		$GLOBALS['error'] 		= 1;
		$GLOBALS['error_type'] 	= "error"; //ok,warn,error,info
		$GLOBALS['error_msg'] 	= "We have no members with that username.";//SPEC($GLOBALS['_LANG']['_zz6']);		
	}
		
		
	}elseif($_POST['action'] == "delete"){
	
		wp_delete_post( $_POST['messageID'], true );
	 
		$GLOBALS['error'] 		= 1;
		$GLOBALS['error_type'] 	= "error"; //ok,warn,error,info
		$GLOBALS['error_msg'] 	= SPEC($GLOBALS['_LANG']['_tpl_messages_error2']);	
	
	}	

}
// LETS VALIDATE THAT THE READER CAN READ THIS MESSAGE
if(isset($_GET['mid']) && is_numeric($_GET['mid']) ){ 

	$msgData = wp_get_single_post( $_GET['mid'] );  
	if(get_post_meta($msgData->ID, 'username', true) != $userdata->user_login){ die("no access"); }


}
 
/* =================== START DISPLAY ================== */ 

if(file_exists(str_replace("functions/","",THEME_PATH)."/themes/".get_option('theme')."/_tpl_messages.php")){
		
	include(str_replace("functions/","",THEME_PATH)."/themes/".get_option('theme').'/_tpl_messages.php');
		
}else{ 
	
	include("template_".strtolower(PREMIUMPRESS_SYSTEM)."/_tpl_messages.php");
	
}
 
?>