<?php

/***************** DO NOT EDIT THIS FILE *************************
******************************************************************

INFORMATION:
------------

This is a core theme file, you should not need to edit 
this file directly. Code changes maybe lost during updates.

LAST UPDATED: June 26th 2011
EDITED BY: MARK FAIL
------------------------------------------------------------------

******************************************************************/

class PremiumPressTheme { 

/******************************************************************* DEPRECIATED IN 6.3 (SEE PPT/CLASS/CLASS_DESING.PHP) */
function Pages($type=0){
	
	global $PPTDesign;
		
	return $PPTDesign->SYS_PAGES();

}
function Categories($ONLYID=0,$STYLE="",$desc=false, $dropnav=false, $onlyshowtickscats=true){

 global $PPTDesign;

return $PPTDesign->SYS_CATEGORIES();
	
}
 
/*************************************************************************************************/

function CountCategorySubs($ID){

	global $wpdb;
	
	$categories= get_categories('child_of='.$ID.'&amp;depth=1&hide_empty=0'); 

	$catcount = count($categories);
	return  $catcount;
}


/*---------------------------- CORE WORDPRESS HOOKS ----------------------------- */
/* ------------------------------------------------------------------------------- */

	function query_orderby($sort) {
	
	global $wpdb;
	
		if(strpos($sort,"postmeta.meta_value") !== false){
			$sort	= str_replace("postmeta.meta_value","postmeta.meta_value+0",$sort);
			return $sort;
		}
	 
		$array_of_numeric_fields = array('ending','price','old_price','hits');  

	
		if(isset($_GET['key']) && in_array($_GET['key'],$array_of_numeric_fields)){ $_GET['quick'] = $_GET['key']; }
	
		if (!isset($_GET['quick'])){ return $sort; } 
       
        if ( (is_tag() OR is_category() OR is_author() OR is_date() OR is_home()) ) {
          
            $ee = explode(" ",$sort);
			$ef = explode(".",$ee[0]);
			 
           if (in_array($_GET['quick'],$array_of_numeric_fields) && $ee[0] == $wpdb->prefix."postmeta.meta_value" ) {
		 
                $sort = "" .  $ee[0] . "+0 ".$ee[1];
				  
           }        
          
        }
  
       return  $sort; 
	}
	
	function query_where($where){ global $wpdb, $wp_query; 

	
	$where = str_replace("'xXx","",str_replace("xXx'","",$where));
 
		if (!isset($_GET['quick'])){ return $where; }
		
	 
	
		// couponpress PRESET SEARCHES
		$where = str_replace("CAST(".$wpdb->prefix."postmeta.meta_value AS CHAR) <= '100a'",$wpdb->prefix."postmeta.meta_value >= 100",$where);
		$where = str_replace("CAST(".$wpdb->prefix."postmeta.meta_value AS CHAR) <= '500a'",$wpdb->prefix."postmeta.meta_value <= 500",$where);
		$where = str_replace("CAST(".$wpdb->prefix."postmeta.meta_value AS CHAR) <= '2000a'",$wpdb->prefix."postmeta.meta_value >= 500 AND ".$wpdb->prefix."postmeta.meta_value <= 2000",$where);	
		$where = str_replace("CAST(".$wpdb->prefix."postmeta.meta_value AS CHAR) <= '5000a'",$wpdb->prefix."postmeta.meta_value >= 2000 AND ".$wpdb->prefix."postmeta.meta_value <= 5000",$where); 	
		$where = str_replace("CAST(".$wpdb->prefix."postmeta.meta_value AS CHAR) >= '10000a'",$wpdb->prefix."postmeta.meta_value >= 10000",$where);
		
		// RP PRICES
		$where = str_replace("CAST(".$wpdb->prefix."postmeta.meta_value AS CHAR) <= '100k'",$wpdb->prefix."postmeta.meta_value <= 100000",$where);
		$where = str_replace("CAST(".$wpdb->prefix."postmeta.meta_value AS CHAR) = '200k'",$wpdb->prefix."postmeta.meta_value >= 100000 AND ".$wpdb->prefix."postmeta.meta_value <= 200000",$where); 
		$where = str_replace("CAST(".$wpdb->prefix."postmeta.meta_value AS CHAR) = '300k'",$wpdb->prefix."postmeta.meta_value >= 200000 AND ".$wpdb->prefix."postmeta.meta_value <= 300000",$where); 	 
 		$where = str_replace("CAST(".$wpdb->prefix."postmeta.meta_value AS CHAR) = '400k'",$wpdb->prefix."postmeta.meta_value >= 300000 AND ".$wpdb->prefix."postmeta.meta_value <= 400000",$where); 
		$where = str_replace("CAST(".$wpdb->prefix."postmeta.meta_value AS CHAR) = '500k'",$wpdb->prefix."postmeta.meta_value >= 400000 AND ".$wpdb->prefix."postmeta.meta_value <= 500000",$where); 		
		$where = str_replace("CAST(".$wpdb->prefix."postmeta.meta_value AS CHAR) = '600k'",$wpdb->prefix."postmeta.meta_value >= 500000 AND ".$wpdb->prefix."postmeta.meta_value <= 600000",$where); 		
		$where = str_replace("CAST(".$wpdb->prefix."postmeta.meta_value AS CHAR) = '700k'",$wpdb->prefix."postmeta.meta_value >= 600000 AND ".$wpdb->prefix."postmeta.meta_value <= 700000",$where); 
		$where = str_replace("CAST(".$wpdb->prefix."postmeta.meta_value AS CHAR) = '700ka'",$wpdb->prefix."postmeta.meta_value >= 700000",$where); 		
		$where = str_replace("CAST(".$wpdb->prefix."postmeta.meta_value AS CHAR) = '800k'",$wpdb->prefix."postmeta.meta_value >= 700000 AND ".$wpdb->prefix."postmeta.meta_value <= 800000",$where);
		$where = str_replace("CAST(".$wpdb->prefix."postmeta.meta_value AS CHAR) = '900k'",$wpdb->prefix."postmeta.meta_value >= 800000 AND ".$wpdb->prefix."postmeta.meta_value <= 900000",$where);		
		$where = str_replace("CAST(".$wpdb->prefix."postmeta.meta_value AS CHAR) = '1000k'",$wpdb->prefix."postmeta.meta_value >= 1000000 AND ".$wpdb->prefix."postmeta.meta_value <= 2000000",$where);		
		$where = str_replace("CAST(".$wpdb->prefix."postmeta.meta_value AS CHAR) = '2000k'",$wpdb->prefix."postmeta.meta_value >= 2000000 AND ".$wpdb->prefix."postmeta.meta_value <= 3000000",$where);		
 
 		

		// BETWEEN
		if(isset($_GET['a']) && is_numeric($_GET['a']) && isset($_GET['b']) && is_numeric($_GET['b']) ){
		
		if(strpos($where, 'xxxx') !== false){
			$where = str_replace("CAST(".$wpdb->prefix."postmeta.meta_value AS CHAR) = 'xxxx'",$wpdb->prefix."postmeta.meta_value >= ".PPTCLEAN($_GET['a'])." AND ".$wpdb->prefix."postmeta.meta_value <= ".PPTCLEAN($_GET['b'])."",$where);	
			// print $where."<br><br>";
		 	}
		}
 
				
	 return $where; }
	
	function query_join($jn){ global $wpdb; return $jn; }

	function query_limits( $limits )	{ return $limits; }

	function BuildSearchString($query_string=""){

	global $wpdb;
	
	$default_searches = array('title','author','modified','comment_count');
 
			if(!empty($_GET['orderby'])){

				if(strlen(trim(strip_tags($_GET['orderby']))) > 1){
				$query_string .= "&orderby=".trim(strip_tags($_GET['orderby']));
				}
				
				if(strlen(trim(strip_tags($_GET['key']))) > 1 && in_array($_GET['key'], $default_searches)){
				$query_string .= "&orderby=".trim(strip_tags($_GET['key']));
				
				}elseif(strlen(trim(strip_tags($_GET['key']))) > 1 && !in_array($_GET['key'], $default_searches)){
				$query_string .= "&meta_key=".trim(strip_tags($_GET['key']));
				}
				
				if(strlen(trim(strip_tags($_GET['meta_value']))) > 1){
				$query_string .= "&meta_value=".trim(strip_tags($_GET['meta_value']));
				}
				if(strlen(trim(strip_tags($_GET['order']))) > 1){
				$query_string .= "&order=".trim(strip_tags($_GET['order']));
				}
				if(strlen(trim(strip_tags($_GET['compare']))) > 1){
				$query_string .= "&meta_compare=".trim(strip_tags($_GET['compare']));
				}

			}else{
			
				$order=trim(get_option("display_defaultorder"));
				$obz = explode("*",$order);
				$query_string .= "&orderby=".$obz[0];
				$query_string .= "&order=".$obz[1];
				
			}
			
			if(isset($_GET['cat']) && is_numeric($_GET['cat'])){
					$query_string .= "&cat=".$_GET['cat'];
			}			
			
			if(isset($_GET['s'])){
					$query_string .= "&s=".$_GET['s'];
			}
			
			return  $query_string."&post_type=post";

}



/*---------------------------- GLOBAL THEME OPTIONS ----------------------------- */
/* ------------------------------------------------------------------------------- */


	function Language(){ 
	
					 
	
		if(!isset($GLOBALS['_LANG'])){
		
		
	
			if($GLOBALS['premiumpress']['language'] ==""){ 
			
				define("THEME_LANG","english");
				
			}else{
			
			
				if ( !isset($_SESSION['lang'] ) && !isset($_REQUEST['l']) ){
				
					// SAVE SESSON FOR LANG
					define("THEME_LANG",$GLOBALS['premiumpress']['language']);
					$_SESSION['lang'] = $GLOBALS['premiumpress']['language'];		
		
				}else{		
		 
						if (isset($_REQUEST['l'])){ 
							unset($_SESSION['lang']);
						}
						if (isset($_SESSION['lang']) && !isset($_REQUEST['l'])){
								$_REQUEST['l'] = $_SESSION['lang'];
								define('THEME_LANG',"language_".$_REQUEST['l']); 
						}
						elseif (isset($_SESSION['lang'] ) && isset($_REQUEST['l'])){
								unset($_SESSION['lang']);
								$_SESSION['lang'] = $_REQUEST['l']; 
								define('THEME_LANG',"language_".$_REQUEST['l']); 
						}
						else{		
						
						 
							if(file_exists(str_replace("functions/","",THEME_PATH) . "/template_".strtolower(constant('PREMIUMPRESS_SYSTEM'))."/language_".strtolower(strip_tags($_REQUEST['l'])).'.php')){
										 
								$_SESSION['lang'] = $_REQUEST['l'];
								define('THEME_LANG',"language_".$_REQUEST['l']);
								 
							} else {
							   define('THEME_LANG',$GLOBALS['premiumpress']['language']);
							}				
						}		
				}		
			
			
			
			
			
			 
			}
			
		
	
		

			$ThisLanguage = THEME_LANG;
			$ThisLanguage = str_replace("language_language","language",$ThisLanguage);	

			if(file_exists(str_replace("functions/","",THEME_PATH) . "/template_".strtolower(constant('PREMIUMPRESS_SYSTEM'))."/".$ThisLanguage.'.php')){
				require_once (str_replace("functions/","",THEME_PATH) . "/template_".strtolower(constant('PREMIUMPRESS_SYSTEM'))."/".$ThisLanguage.'.php');

				if(THEME_LANG == "language_english"){
						$GLOBALS['_LANG'] = $LANG_;
				}else{ 
						$GLOBALS['_LANG'] = SPEC($LANG_);
				}
			}
		}	
		
	 
		
		 	
		
		
	}




/*---------------------------- GENERAL DISPLAY CALLS ----------------------------- */
/* ------------------------------------------------------------------------------- */


	function cincopa($code,$show=false){
	
	if(strlen($code) < 2){ return ""; }
	
	 global $wpdb;
	 
		if(get_option("enable_system_cincopa") =="yes"){	
	 
			$uni = uniqid('');
			$ret = '<div id="_cp_widget_'.$uni.'"><img src="http://www.cincopa.com/wpplugin/runtime/loading.gif" style="border:0;" alt="Powered by Cincopa WordPress plugin" /></div>
			<script src="http://www.cincopa.com/wpplugin/runtime/libasync.js" type="text/javascript"></script>
			<script type="text/javascript">
			cp_load_widget("'.urlencode($code).'", "_cp_widget_'.$uni.'");</script>	';
			$ret .= '<noscript>Click <a href="http://www.cincopa.com/wpplugin/view.aspx?fid='.urlencode($match[0]).'">here</a> to open the gallery.<br />';
			$ret .= '</noscript>';
			
			if($show){
				print $ret;
			}else{
				return $ret;
			}		
			
		
		}else{
		
			return "";
		
		}
	
	
	}



	function Logo($return=""){
 
		if(isset($GLOBALS['premiumpress']['logo_url']) && strlen($GLOBALS['premiumpress']['logo_url']) > 1){ 
			
			if(substr($GLOBALS['premiumpress']['logo_url'],0,1) == ","){
				$GLOBALS['premiumpress']['logo_url'] = substr($GLOBALS['premiumpress']['logo_url'],1);
			}
 
			$logo = $this->ImageCheck($GLOBALS['premiumpress']['logo_url'],"full");

		}else{
 			if(isset($GLOBALS['premiumpress']['theme']) && $GLOBALS['premiumpress']['theme'] == ""){ $GLOBALS['premiumpress']['theme'] = "default"; }
			$logo = $GLOBALS['template_url']."/themes/".$GLOBALS['premiumpress']['theme']."/images/logo.png";
		}	
		
		if($return){
		return $logo;
		}else{
		echo $logo;
		}
	}

	function Copyright(){
	
	global $wpdb;
	
	if(get_option("removecopyright") == "yes"){ return ""; }
		
		$STRING = "";
		$STRING .= 'Developed By <a href="http://www.'.''.'premiumpress.com/premium-wordpress-themes/" target="_blank">Premium Wordpress Themes</a>';

		print $STRING;	
	
	}




	function GetCustomFieldList($value1="", $key="meta_key"){
	
		global $wpdb;
		
		$SQL = "SELECT ".$key." FROM $wpdb->postmeta WHERE meta_key !='_".$wpdb->prefix."page_template' AND meta_key !='_edit_last' AND meta_key !='_edit_lock' GROUP BY ".$key."";
	
		$last_posts = (array)$wpdb->get_results($SQL);
		
		print "<option value='title' ";if($value1 == "title"){print "selected"; } print ">Post Title</option>";
		print "<option value='author'";if($value1 == "author"){print "selected"; } print ">Post Author</option>";
		print "<option value='modified'";if($value1 == "modified"){print "selected"; } print ">Last Modified</option>";
		print "<option value='comment_count'";if($value1 == "comment_count"){print "selected"; } print ">Comment Count</option>";
		 
	
		foreach($last_posts as $value){
		
			if($value1 == $value->meta_key){
				print "<option value='".$value->meta_key."' selected>".$value->meta_key."</option>";
			}else{
				print "<option value='".$value->meta_key."'>".$value->meta_key."</option>";
			}		
		
		}	
	
	}



	function MoneyFormat($num, $noV=""){
	 
		if($num > 999){
		
			$num = @number_format($num,2, '.', ',');		
			$num = str_replace(",","",$num);
	 
		}else{
		
			$num = @number_format($num,2, '.', ',');
		
		}
		
		if(substr($num,-3) ==".00") {
			$num = substr($num, 0, strlen($num)-3); 
		} 
		
		return $num;
	 
	}


	function GetCustomFields($post,$FieldValues){

	global $wpdb; $row=1;

	if($FieldValues ==""){ 
		$FieldValues = get_option("customfielddata");
	}

	if(is_array($FieldValues)){ 

		foreach($FieldValues as $key => $field){

			if(isset($field['show']) && $field['show'] == 1 ){ 				 
			
			$imgArray = array('jpg','gif','png');

			$value = $this->GetListingCustom($post->ID,$field['key'] );
 
			if(is_array($value) || strlen($value) < 1){   }else{			
		
				print "<div class='CustomRow ";
				if($row%2){ print "left"; }else{ print "right"; }
				print "'><span>".$field['name']."</span> ";
		
				switch($field['type']){
				 case "textarea": {			
					print "<br />".nl2br(stripslashes($value));
				 } break;
				 case "list": {
					print  $value;
				 } break;
				 default: {
					
					$pos = strpos($value, 'http://'); 					
					if($field['key'] == "skype"){
						print "<a href='skype:".$value."?add'>" .  $value ."</a>";
					}elseif ($pos === false) {
						print  $value;
					}elseif(in_array(substr($value,-3),$imgArray)){
						print "<img src='".strip_tags($value)."' style='max-width:250px;margin-left:20px;'>";
					}else{
						print "<a href='".$value."' target='_blank'";
						if($GLOBALS['directorypress']['nofollow'] =="yes"){ print 'rel="nofollow"'; }
						print ">" .  $value ."</a>";				
					} 
					
				 }
		
				}
				$row++;
				print "</div>";
				
				}

				} 
			}
		}
	
	}

	function Price($price, $code="",$lor="l",$skip=0,$digs=2,$forceZero=false){
	
	 if(isset($GLOBALS['premiumpress']['currency_format']) && strlen($GLOBALS['premiumpress']['currency_format']) > 0){ $digs=$GLOBALS['premiumpress']['currency_format']; }  
	  
	if(strtolower(constant('PREMIUMPRESS_SYSTEM')) == "realtorpress"){ 
	$digs=0;
	}
	
	
	if($price == "0" || $price == ""){ 
	
		if($forceZero){ 	
			if($lor =="l"){
				return $code.$price;
			}else{
				return $price.$code;
			}		
		
		 }else{
		 
		 	return;
		 
		 } 
	 
	 } 
	
	//if(!is_numeric($price)){ return $price; }

		if(is_numeric($price)){
		
			if($price > 999 && $skip == 0){
			
				$price = @number_format($price,$digs, '.', ',');		
				$price = str_replace(",","",$price);
		 
			}else{
			
				$price = @number_format($price,$digs, '.', ',');
			
			}
		} 
 
		
		 
		if($lor =="l"){
			return $code.$price;
		}else{
			return $price.$code;
		}
		
	}

	function Articles($num=10,$details=false,$date=false){
			
		global $wpdb;
		
		wp_reset_query();
		
		$STRING = "";
		
		if($num == ""){$num=1; }		
		

		$paged = (get_query_var('paged')) ? get_query_var('paged') : 1;
		$posts = query_posts('post_type=article_type&posts_per_page='.$num);		

		foreach($posts as $post){
		
			if($date){  $dd = "<div class='time'>".get_the_time('l, F jS',$post)."</div>"; }else{  $dd = ""; }
		
			if($details){
			
				$cont = get_post_meta($post->ID, "short_desc", true);
				if(strlen($cont) < 5){
				$cont = substr(strip_tags($post->post_content),0,170);
				}

				$STRING  .="<li><h3><a href='".get_permalink( $post->ID )."'>".$post->post_title."</a></h3>".$dd."<img src='".$this->Image($post,"url")."'/>".$cont."</li>";			
			 
			}else{ 
			
			
				$STRING  .="<li><a href='".get_permalink( $post->ID )."'>".$post->post_title."</a>".$dd."</li>";			
			
			}
		
		}

		wp_reset_query();
		
		return $STRING;
	
	}


 
	function multisort($array, $sort_by) {
		foreach ($array as $key => $value) {
			$evalstring = '';
			foreach ($sort_by as $sort_field) {
				$tmp[$sort_field][$key] = $value[$sort_field];
				$evalstring .= '$tmp[\'' . $sort_field . '\'], ';
			}
		}
		$evalstring .= '$array';
		$evalstring = 'array_multisort(' . $evalstring . ');';
		eval($evalstring);
	
		return $array;
	}

	function FilterPath(){
	
		$path=dirname(realpath($_SERVER['SCRIPT_FILENAME']));
		$path_parts = pathinfo($path); 
		if($path == ""){
			return $_SERVER['DOCUMENT_ROOT'];
		}else{
			$path = $path_parts['dirname'];
			if($path_parts['basename'] != ""){ $path .= "/".$path_parts['basename']; }
			
			/*if(substr($path£¬-1) != "/" || substr($path£¬-1) != "\""){
			$path .="/";
			}*/
			return $path;
		}
		
	}


 
 
	function ImageCheck($img,$ex="thumb",$addedSize=""){

	global $wpdb; 

		$pos = stripos($img, "http");
		if ($pos !== false) {
			if(substr($img,0,-3) != "."){ return $img; }else{ return $img."?"; }	
		}else{
		
		if($ex == "full" || !isset($GLOBALS['premiumpress']['thumbresize']) || $GLOBALS['premiumpress']['thumbresize'] == "off"){ $extra = ""; }else{ $extra= "_tbs.php?src="; } 
		

			if(!isset($GLOBALS['premiumpress']['imagestorage_link'])){ 
				$rStr = get_option('imagestorage_link').$extra.str_replace(",","",$img);
			}else{
				
				$rStr = $GLOBALS['premiumpress']['imagestorage_link'].$extra.str_replace(",","",$img);
			}	
				
			
			if($ex == "full" || $GLOBALS['premiumpress']['thumbresize'] == "off"){ return $rStr ."?"; }else{ return $rStr.$addedSize; }
		}
	}


	function Image($data,$type="m",$addedSize=""){

	global $wpdb; $useAPI = false;

	if(!isset($GLOBALS['premiumpress']['imagestorage_link'])){ 
		$GLOBALS['premiumpress']['imagestorage_link'] = get_option('imagestorage_link');
	}
	
	if(isset($GLOBALS['premiumpress']['previewimage_type']) || $GLOBALS['premiumpress']['previewimage_type'] == ""){
		$GLOBALS['premiumpress']['previewimage_type'] = get_option("display_previewimage_type");
	}
 
		if(is_object($data) && is_numeric($data->ID)){ $THISID = $data->ID;	}elseif(is_numeric($data)){ $THISID = $data;	}elseif(isset($data['ID'])){ $THISID = $data['ID'];	}
 
		if(!isset($THISID)){
	
			if($type == "t" && strlen($data) > 2){
	
				return $this->ImageCheck($data);
			
			}else{		
				return $GLOBALS['premiumpress']['imagestorage_link']."na.gif?";
			} 
	
		}else{
	
			$try = "";
	
			switch($type){
				case "s": { $try 		= get_post_meta($THISID, "thumbnail", true);		} break;
				case "m": { $try 		= get_post_meta($THISID, "image", true);			 } break; 
				case "l": { $try 		= get_post_meta($THISID, "featured_image", true);  	} break;
				case "url": { 					
					$try 			= get_post_meta($THISID, "image", true);	
					if($try == ""){
						$useAPI = true;
						$try 		= get_post_meta($THISID, "url", true);	
					}				
				} break;
				case "full": { $try 		= get_post_meta($THISID, "image", true);  
				
				if($try == ""){return $GLOBALS['premiumpress']['imagestorage_link']."na.gif?";}
				return $this->ImageCheck($try,"full"); 	} break;
				default: {  $try 		= get_post_meta($THISID, "image", true);			} break;
			}
	
			if($try == ""){
				$try 		= get_post_meta($THISID, "image", true);
			}
	 
			if($try == ""){
	
				return $GLOBALS['premiumpress']['imagestorage_link']."na.gif?";
	
			}else{
	
				if($type == "url" && $useAPI){
 
					if($GLOBALS['premiumpress']['previewimage_type'] =="custom"){
					
						if(!isset($GLOBALS['premiumpress']['STW_access_key'])){
							$GLOBALS['premiumpress']['STW_access_key'] =  get_option("STW_access_key");
						}
						
						if(!isset($GLOBALS['premiumpress']['STW_secret_key'])){
							$GLOBALS['premiumpress']['STW_secret_key'] =  get_option("STW_secret_key");
						}
 
						$args = array();
						$args['custom'] 	= "yes";
						$args['key'] 		= $GLOBALS['premiumpress']['STW_access_key'];
						$args['ID'] 		= $GLOBALS['premiumpress']['STW_secret_key'];
  
						return str_replace(".jpg.jpg",".jpg",str_replace(".png.jpg",".png",str_replace(".gif.jpg",".gif",$this->SaveImage($try,$args))));


					}elseif($GLOBALS['premiumpress']['previewimage_type'] == "off" || $GLOBALS['premiumpress']['previewimage_type'] ==""){
					
					return $this->ImageCheck($try,"",$addedSize);
					
					}else{
						return str_replace(".jpg.jpg",".jpg",str_replace(".png.jpg",".png",str_replace(".gif.jpg",".gif",$this->SaveImage($try))));
					}
	
				}else{
	
					return $this->ImageCheck($try,"",$addedSize);
	
				}	
				
			}
	
		}
 
	}

	function ImageGallery($data,$s1="rel='prettyPhoto[gallery]'",$s2="class='galleryimg'"){

		$STRING = "";

		$try = get_post_meta($data->ID, "images", true);
 
		if($try == ""){

			return $STRING;

		}else{

			$images = explode(",",$try);
			foreach($images as $img){ if(strlen($img) > 2){

				$STRING .= "<li><a href='".$this->ImageCheck($img)."' ".$s1."><img src='".$this->ImageCheck($img)."' ".$s2."></a></li>";	
			
			} }		
		}

		return $STRING;
	
	}


	function BannerZone($cat_id){
	
	global $wpdb;

	
	return stripslashes(get_option("advertising_zone_".$cat_id));	
	
	}

	function Banner($type){
	
	global $wpdb, $post;
	
 
	 
	if(isset( $post->post_title) && strlen($post->post_title) > 4){
		$findme   = array('terms','privacy');
		foreach($findme as $key){
			$pos = strpos(strtolower($post->post_title), $key);				 
			if ($pos === false) {} else {return "";}
		}
 	}
 
		if(get_option('advertising_'.$type.'_checkbox') !=1){  return "";}
		
		if (get_option('advertising_'.$type.'_adsense') <> "") { 
					
				echo stripslashes(get_option('advertising_'.$type.'_adsense')); 
				
		} else { 
					
			if (!get_option('advertising_'.$type.'_url') || !get_option('advertising_'.$type.'_dest')) {  
						
			 } else { 	
						
				echo '<a href="' . get_option("advertising_".$type."_url") . '" target="_blank"><img src="' . get_option("advertising_".$type."_dest") . '" border="0" /></a>';
							
			} 
		}
	
		 
	}


	function TimeDiff($date,$admin=false)
	{
		if(empty($date)) {
			return false;
		}
	 
		if($admin){
				$periods         = array("second", "minute", "hour", "day", "week", "month", "year", "decade");
		
		}else{
		
			$periods         = array($GLOBALS['_LANG']["second"], $GLOBALS['_LANG']["minute"], $GLOBALS['_LANG']["hour"], $GLOBALS['_LANG']["day"], $GLOBALS['_LANG']["week"], $GLOBALS['_LANG']["month"], $GLOBALS['_LANG']["year"], $GLOBALS['_LANG']["decade"]);
			$periodss         = array($GLOBALS['_LANG']["seconds"], $GLOBALS['_LANG']["minutes"], $GLOBALS['_LANG']["hours"], $GLOBALS['_LANG']["days"], $GLOBALS['_LANG']["weeks"], $GLOBALS['_LANG']["months"], $GLOBALS['_LANG']["years"], $GLOBALS['_LANG']["decades"]);
			
		}
		$lengths         = array("60","60","24","7","4.35","12","10");
	 
		$now             = time();
		$unix_date         = strtotime($date);
	 
		if(empty($unix_date)) {    
			return false;
		}
	 
		if($now > $unix_date) {    
			$LAND_val = "expiresinB"; 
			$difference     = $now - $unix_date;
			$tense         = "ago"; //
	 
		} else {
			$LAND_val = "expiresinA";
			$difference     = $unix_date - $now;
			$tense         = "";
		}
	 
		for($j = 0; $difference >= $lengths[$j] && $j < count($lengths)-1; $j++) {
			$difference /= $lengths[$j];
		}
	 
		$difference = round($difference);
	 
		if($difference != 1) {
			$periods[$j] = $periodss[$j];
		}
	 
		return str_replace("%a","$difference $periods[$j]",$GLOBALS['_LANG'][$LAND_val]);
	}



	function Get_Cateory($req){
	
		global $wpdb; $catID=0;
	
		if(isset($req['cat'])){
			$catID = $req['cat'];
		}else{
	
		$catName1 = explode("/",$_SERVER["REQUEST_URI"]);			
		$aaCount = count($catName1);
		if($aaCount > 1){

 
			if($catName1[$aaCount-1]  != ""){
			$catName1[1] = $catName1[$aaCount-1];
			}
			if($catName1[$aaCount-2]  != ""){
			$catName1[1] = $catName1[$aaCount-2];
			}

		 
			if(isset($catName1[1])){
		
				$result = mysql_query("SELECT term_id FROM $wpdb->terms WHERE slug= ('".strip_tags(PPTCLEAN($catName1[1]))."' ) LIMIT 1", $wpdb->dbh) or die(mysql_error().' on line: '.__LINE__);
				$array = mysql_fetch_assoc($result);
				if ( is_numeric($array['term_id']) ){
					$catID = $array['term_id'];
				}	
			}
			
			if(isset($catName1[0]) && $catID==0){
		
				$result = mysql_query("SELECT term_id FROM $wpdb->terms WHERE slug= ('".strip_tags(PPTCLEAN($catName1[0]))."' ) LIMIT 1", $wpdb->dbh) or die(mysql_error().' on line: '.__LINE__);
				$array = mysql_fetch_assoc($result);
				if ( is_numeric($array['term_id']) ){
					$catID = $array['term_id'];
				}	
			}
	 
		}
	
		if($catID != 0){
			$cat = get_category($catID);
			return $cat;
		}
}
	}



	function auth_redirect_login() {

		global $wpdb;

		$user = wp_get_current_user();
		if ( $user->id == 0 ) {
			nocache_headers();
			wp_redirect(get_option('siteurl') . '/wp-login.php?redirect_to=' . urlencode($_SERVER['REQUEST_URI']));
			exit();
		}

	}

	function CategoryFromID($id=0){
 
		global $wpdb;	 $string="";
		
		if(is_array($id)){
		
			foreach($id as $cid){
			
				if(is_numeric($cid) && $cid !=0 ){
			
					$SQL = "SELECT name FROM $wpdb->terms WHERE $wpdb->terms.term_id = '". $cid ."' LIMIT 1";	
		 
					$dd = (array)$wpdb->get_results($SQL);
					
					$string .= "<a href='".get_category_link( $cid )."' target='_blank'>".$dd[0]->name."</a> ";	
				
				}
			
			}
		
		}else{
			
			$SQL = "SELECT name FROM $wpdb->terms WHERE $wpdb->terms.term_id = '". $id ."' LIMIT 1";	
	 
			$dd = (array)$wpdb->get_results($SQL);
	
			$string = $dd[0]->name;	
		
		}
		
		return $string;
	
	}

	function CategoryList($id=0,$showAll=false,$showExtraPrice=false,$TaxType=""){

		global $wpdb; $exclueMe=array();
		$CCode = get_option("currency_code");
		$ShowCatCount = get_option("display_categories_count");
		
		$hiera = '&hide_empty=0';
		
		if($showAll == "toponly"){
		$hiera = '&hide_empty=0';
		}elseif($showAll){
		$extra="";
		}else{
		$extra="&exclude=".get_option('article_cats');
		}
		

		$catlist="";
 		$Maincategories = get_categories('pad_counts=1&use_desc_for_title=1&hierarchical=0'.$TaxType.$hiera.$extra); 
		 
		$Maincatcount = count($Maincategories);	 
		foreach ($Maincategories as $Maincat) { 
		if($Maincat->parent ==0){
		if(strlen($Maincat->cat_name) > 0){	
		 
			if($showExtraPrice == 1){ $price  = get_option('CatPrice_'.$Maincat->cat_ID); }else{ $price  = ""; }
			if($price == ""){ $extra1 = ""; }else{ $extra1 = " + ".$CCode.$price; }	
		
			if($id == $Maincat->cat_ID){ $extra="selected"; }else{ $extra=""; }
			$catlist .= '<option value="'.$Maincat->cat_ID.'"'.$extra.'>';
			$catlist .= $Maincat->cat_name;
			if($ShowCatCount =="yes"){ $catlist .= " (".$Maincat->count.')'; }
			$catlist .= $extra1."";
			$catlist .= '</option>';
				$currentcat=get_query_var('cat');
				$categories= get_categories('pad_counts=1&child_of='.$Maincat->cat_ID.'&depth=1'.$TaxType.'&hide_empty=0&hierarchical=0'); 
				$catcount = count($categories);		
				$i=1;
				if(count($categories) > 0){
				 
					foreach ($categories as $cat) {		
			 		if($cat->cat_ID == $id){ $extra ="selected"; }else{ $extra =""; }
					
						if($showExtraPrice == 1){ $price  = get_option('CatPrice_'.$cat->cat_ID); }else{ $price  = ""; }
						if($price == ""){ $extra1 = ""; }else{ $extra1 = " + ".$CCode.$price; }	
						
						$currentcat1=get_query_var('cat');
						$categories1= get_categories('pad_counts=1&child_of='.$cat->cat_ID.'&depth=1'.$TaxType.'&hide_empty=0&hierarchical=0'); 
						$catcount1 = count($categories); 
						
							if(!in_array($cat->cat_ID,$exclueMe)){ 
							
								if( ( $showAll != "toponly" ) || ( $showAll == "toponly" && $cat->count > 0 ) ){
								
									$catlist .= '<option value="'.$cat->cat_ID.'" '.$extra.'> -> ';
									$catlist .= $cat->cat_name;
									if($ShowCatCount =="yes"){ $catlist .= " (".$cat->count.')'; }
									$catlist .= $extra1.'</option>';
								}	
							}					 
							$i++;
						
						
							if(count($categories1) > 0){
							
								foreach ($categories1 as $cat1) {	
									
									if($cat1->cat_ID == $id){ $extra ="selected"; }else{ $extra =""; }							
									if($showExtraPrice == 1){ $price  = get_option('CatPrice_'.$cat1->cat_ID); }else{ $price  = ""; }
									if($price == ""){ $extra1 = ""; }else{ $extra1 = " + ".$CCode.$price; }	
									
									$currentcat2	= get_query_var('cat');
									$categories2	= get_categories('pad_counts=1&child_of='.$cat1->cat_ID.'&depth=1'.$TaxType.'&hide_empty=0'); 
									$catcount2 		= count($categories2);	
									
									
									if(!in_array($cat1->cat_ID,$exclueMe)){
										if( ( $showAll != "toponly" ) || ( $showAll == "toponly" && $cat1->count > 0 ) ){
											$catlist .= '<option value="'.$cat1->cat_ID.'" '.$extra.'> --> ';
											$catlist .= $cat1->cat_name;
											if($ShowCatCount =="yes"){ $catlist .= " (".$cat1->count.')'; }
											$catlist .= $extra1.'</option>';
											array_push($exclueMe,$cat1->cat_ID);
										} 
									}					 
									$i++;
									
									
									
										if(count($categories2) > 0){
										
											foreach ($categories2 as $cat2) {	
												
												if($cat2->cat_ID == $id){ $extra ="selected"; }else{ $extra =""; }							
												if($showExtraPrice == 1){ $price  = get_option('CatPrice_'.$cat2->cat_ID); }else{ $price  = ""; }
												if($price == ""){ $extra1 = ""; }else{ $extra1 = " + ".$CCode.$price; }	
												
												$currentcat3	= get_query_var('cat');
												$categories3	= get_categories('pad_counts=1&child_of='.$cat1->cat_ID.'&depth=1'.$TaxType.'&hide_empty=0'); 
												$catcount3 		= count($categories3);	
												
												
												if(!in_array($cat2->cat_ID,$exclueMe)){
												$catlist .= '<option value="'.$cat2->cat_ID.'" '.$extra.'> ---> ';
												$catlist .= $cat2->cat_name;
												if($ShowCatCount =="yes"){ $catlist .= " (".$cat2->count.')'; }
												$catlist .= $extra1.'</option>';
												array_push($exclueMe,$cat2->cat_ID);
												} 					 
												$i++;
												
												
												
													if(count($categories3) > 0){
													
														foreach ($categories3 as $cat3) {	
															
															if($cat3->cat_ID == $id){ $extra ="selected"; }else{ $extra =""; }							
															if($showExtraPrice == 1){ $price  = get_option('CatPrice_'.$cat3->cat_ID); }else{ $price  = ""; }
															if($price == ""){ $extra1 = ""; }else{ $extra1 = " + ".$CCode.$price; }	
															 
															
															if(!in_array($cat3->cat_ID,$exclueMe)){
															$catlist .= '<option value="'.$cat3->cat_ID.'" '.$extra.'> ----> ';
															$catlist .= $cat3->cat_name;
															if($ShowCatCount =="yes"){ $catlist .= " (".$cat3->count.')'; }
															$catlist .= $extra1.'</option>';
															array_push($exclueMe,$cat3->cat_ID);
															} 					 
															$i++;
														}
													
													}
												
												
												
												
												
												
												
												
												
											}
										
										}									
									
									
									
									
									
									
									
									
									
									
									
								}
							
							}
							
							
								
						
								
					}				 
				}		
			} 
		}
 	}

	return $catlist;

	}


	function SubmitForm_customfields($data){

	global $wpdb; $i = 0; $FieldValues = get_option("customfielddata");
	
	if(is_array($FieldValues)){ foreach($FieldValues as $key => $field){

		if(isset($field['enable']) && $field['enable'] == 1 && ( isset($field['pack'.$_POST['packageID']]) && $field['pack'.$_POST['packageID']] == 1 || $GLOBALS['premiumpress']['display_packages'] == 0) ){
	
			echo '<div class="input text"><label>'.$field['name'].'</label>';
			switch($field['type']){
			 case "textarea": {
				echo '<textarea class="adfields" name="custom['.$i.'][value]" rows="10" cols="48">';
				if(isset($_POST['action']) && !isset($data) ){ echo $_POST['custom'][$i]['value']; }elseif(isset($data)){ echo $this->GetListingCustom($_GET['eid'],$field['key'] );  }else{ echo $field['value'];} 
				echo '</textarea>';
			 } break;
			 case "list": {
				if(isset($data)){$listval = $this->GetListingCustom($_GET['eid'],$field['key'] ); }else{ $listval=""; }
				$listvalues = explode(",",$field['value']);
				echo '<select name="custom['.$i.'][value]">';
				foreach($listvalues as $value){ 
					if($listval ==  $value){ 
					echo '<option value="'.$value.'" selected>'.$value.'</option>'; 
					}else{
					echo '<option value="'.$value.'">'.$value.'</option>'; 
					}
				}
				echo '</select>';			
			 } break;
			 default: {	
				echo '<input type="text" class="adfields" name="custom['.$i.'][value]" size="55" maxlength="100" value="';
				if(isset($_POST['action']) && !isset($data) ){ echo $_POST['custom'][$i]['value']; }elseif(isset($data)){ echo $this->GetListingCustom($_GET['eid'],$field['key'] );  }else{ echo $field['value'];} 
				echo '">';
			 }
			}	
			echo '<input type="hidden"  name="custom['.$i.'][name]" value="'.$field['key'].'" /></div>';  
			$i++;
		}
	  } 
	 }
	}
 


	function uploadimage($FILE){
	
		global $wpdb, $current_user; $error=""; $i=0; $currentCount=0;
		
		// LOAD IN THE IMAGE RESIZE CLASS FOR LATER
		$image = new ResizeImage(); $STORAGEPATH = get_option('imagestorage_path');
	
		if($FILE['d']['name'][0] ==""){ return; }
		
		// HERE WE CAN DECIDE WHAT FILE FORMATS ARE ACCEPTABLE
		$permitted_files = array('image/jpeg','image/pjpeg','image/png' ); //,'image/svc','video/mov','video/mpeg4','video/mp4','video/wmv','application/pdf' 'image/gif','image/tiff','image/ico'
		
		// GET THE MAX NUMBER OF IMAGES
		$STOPCOUNT = get_option('display_fileupload_max'); if($STOPCOUNT == ""){$STOPCOUNT=5; }		
		
		// GET THE TOTAL NUMBER OF IMAGES
		if(isset($_POST['eid']) && is_numeric($_POST['eid'])){
			$currentImages = get_post_meta($_POST['eid'], 'images', true);
			if(strlen($currentImages) < 2){ 
				$currentImages=""; 
			}else{
				$currentCount = count(explode(",",trim($currentImages)));
				$STOPCOUNT = $STOPCOUNT - $currentCount;		
			}
		}

	//die($STOPCOUNT." ".$currentCount);
		
		$RunningCount=0;
		foreach($FILE as $single_file){ 
		 
				$countArray = count($single_file['name']);
			 
				for($a=0; $a < $countArray; $a++){
				
				if($RunningCount < $STOPCOUNT){		
		
				// CHECK THE IMAGE FORMAT
				 if(in_array($single_file['type'][$i], $permitted_files)){ $CanContinue=1;}else{ $CanContinue=0; }
								
					if($CanContinue ==1 && strlen($single_file['tmp_name'][$i]) > 0){
		 
						$copy = @copy($single_file['tmp_name'][$i], $STORAGEPATH.$single_file['name'][$i]);
				
						if($copy){
							
							// IF THE IMAGE SIZE IS GREATER THAN 400, RESIZE IT
							$image_info = @getimagesize($STORAGEPATH.$single_file['name'][$i]);
							if(is_array($image_info) && isset($image_info['mime']) && $image_info[0] > 600){
								$image->load($STORAGEPATH.$single_file['name'][$i]);
								$image->resizeToWidth(600);
								$image->save($STORAGEPATH.$single_file['name'][$i]);							
							}						   
							
							// NOW LETS RENAME IT
							$bits = explode(".",$single_file['name'][$i]);							
							$NewName =  $current_user->ID."-".$i.date("YmdHis").".".$bits[1];							
							rename ($STORAGEPATH.$single_file['name'][$i], $STORAGEPATH.$NewName);
					
							$error .= $NewName.","; //$single_file['name'][$i].",";
			 
						}			
					}
										
					$i++;				
				}	
				
				$RunningCount++;
			} 		
		}
 
	return $error;
	 
	}

	function deletephoto($post_id, $imagename,$user_id){
	 
		global $wpdb; $userdata; $string=""; $i=0;

		$this->authme($post_id,$user_id);
	
		$image = get_post_meta($post_id, "image", true); 
		$image_s = get_post_meta($post_id, "images", true);
		$pics = explode(",", $image_s);
		
		foreach($pics as $pic) {
	
				if($pic != $imagename){ $string .= $pic.","; }
		}
		$string = str_replace(",,",",",trim($string));
		
		while($i < count($pics)){		
			if(substr($string, -1) == ","){
				$string = substr($string, 0, -1);
			}
			$i++;
		}
	 //die($string);
		update_post_meta($post_id, 'images', $string);
	
		if($image == $imagename){
			update_post_meta($post_id, 'image', $pics[0]);	
		}
	 
		return 1;
	}
	
	
	
	function SetDisplayPhoto($post_id, $imagename,$user_id){
	 
		global $wpdb; $userdata; $string="";

		$this->authme($post_id,$user_id);
	
		update_post_meta($post_id, 'image', $imagename);		 
	 
		return 1;
	}

	function Action_Validate(){

		global $wpdb;
		
		if(strlen($_POST['form']['title']) < 5){ return "The title is too short."; }
	
		if(strlen($_POST['form']['short']) < 5){ return "The short description is too short"; }	
		
		return true;
	}


	function Action_Edit(){ 
 
		global $wpdb; global $userdata; get_currentuserinfo();

		$DefaultFields = array("title","description","short","tags");

		$catArray = array($_POST['CatSel'][1],$_POST['CatSel'][2],$_POST['CatSel'][3]);
 
		$NewcatArray = array();
		foreach($catArray as $nc){
		if($nc !=""){ $NewcatArray[] = $nc; }
		}

		if(get_option("display_fileupload") =="yes"){
			$uploaded_files = $this->uploadimage($_FILES);
		}
 
		if(isset($_POST['form']['country']) && !is_numeric($_POST['form']['country'])){
			  $_POST['form']['tags'] .= ",".$_POST['form']['country'];
		}
		
		if(isset($_POST['form']['state']) && !is_numeric($_POST['form']['state'])){
			  $_POST['form']['tags'] .= ",".$_POST['form']['state'];
		}	
 
		$my_post = array();
		$my_post['ID'] 				= $_POST['eid'];
		$my_post['post_title'] 		= PPTOUTPUT($_POST['form']['title']);
		$my_post['post_content'] 	= $_POST['form']['description'];
		$my_post['post_excerpt'] 	= PPTOUTPUT($_POST['form']['short']);
		$my_post['post_author'] 	= $user_ID;
		$my_post['post_category'] 	= $NewcatArray;		
		$my_post['tags_input'] 		= PPTOUTPUT($_POST['form']['tags']);
				
		if(get_option("display_listing_status") != ""){
			$my_post['post_status'] 	= get_option("display_listing_status");
		}
		
		wp_update_post( $my_post );
		
		$_POST['form']['price'] = str_replace(",","",$_POST['form']['price']);
		
		if(isset($_POST['form']['country']) && !is_numeric($_POST['form']['country'])){
			  update_post_meta($_POST['eid'], "country",  PPTOUTPUT($_POST['form']['country']));	
		}
		
		if(isset($_POST['form']['state']) && !is_numeric($_POST['form']['state'])){
			  update_post_meta($_POST['eid'], "state",  PPTOUTPUT($_POST['form']['state']));	
		}
 
		if(is_array($_POST['custom']) ){
			foreach($_POST['custom'] as $in_array){
			 
				update_post_meta($_POST['eid'], $in_array['name'],  $this->nl2br2($in_array['value']));				
			 }	
		}

		if(is_array($_POST['form']) ){
			foreach($_POST['form'] as $key => $val){
				if(!in_array($key,$DefaultFields)){
					update_post_meta($_POST['eid'], $key,  PPTOUTPUT($val));			
				}	
			}	
		}

		if(strlen($uploaded_files) > 2 ){		
			$images = get_post_meta($_POST['eid'], "images", true);	
			update_post_meta($_POST['eid'], 'images', $uploaded_files.$images);		
			 
			$imgS = explode(",",$uploaded_files.$images);
			update_post_meta($_POST['eid'], 'image', $imgS[0]);
		}	
		
		
		if(isset($_POST['Dir']['state']) && !is_numeric($_POST['Dir']['state'])){
			  $_POST['form']['tags'] .= ",".$_POST['form']['state'];
			}	

		return "Changed Saved";

	}
	
	function nl2br2($string) {
	
    $string = str_replace('\\r\\n', '<br>', $string);
    $string = str_replace('', '<br>', $string);
    $string = str_replace('', '', $string);
	$string = stripslashes($string);
    return $string;
	
	}
	
	function CheckPackagePrice(){
	
	global $wpdb; $Total = 0;
	
	$PACKAGE_OPTIONS = get_option("packages");

	$Total = $PACKAGE_OPTIONS[$_POST['packageID']]['price'];
	
	$catArray = array($_POST['CatSel'][1],$_POST['CatSel'][2],$_POST['CatSel'][3]);
	
	// CHECK FOR ADDITONAL CATEGORY PRICES
	$runningCount = 0;
	foreach($catArray as $CATID){
		$price  = get_option('CatPrice_'.$CATID);
		if($price == ""){ $runningCount += 0; }else{ $runningCount += $price; }	
	}
	
	$Total += $runningCount;
	
	return $Total;
	
	}
	

	function Action_Add(){  
	
 
		if(isset($_POST['form']['trackingID'])){
		
			$ALREADYADDED = $this->CheckExists("trackingID",$_POST['form']['trackingID']);
 
			if(is_numeric($ALREADYADDED)){ return $ALREADYADDED; }

			global $wpdb; global $userdata; get_currentuserinfo();
	
			$DefaultFields = array("title","description","short","tags");
	
			if(get_option("display_fileupload") =="yes"){
				$uploaded_files = $this->uploadimage($_FILES);
			}
			
			if(isset($_POST['form']['country']) && !is_numeric($_POST['form']['country'])){
			  $_POST['form']['tags'] .= ",".$_POST['form']['country'];
			}
		
			if(isset($_POST['form']['state']) && !is_numeric($_POST['form']['state'])){
			  $_POST['form']['tags'] .= ",".$_POST['form']['state'];
			}	 
	
			$catArray = array($_POST['CatSel'][1],$_POST['CatSel'][2],$_POST['CatSel'][3]);
			
			$NewcatArray = array();
			foreach($catArray as $nc){
			if($nc !=""){ $NewcatArray[] = $nc; }
			}
	
			$my_post = array();
			$my_post['post_title'] 			= $_POST['form']['title'];
			$my_post['post_content'] 		= $_POST['form']['description'];
			$my_post['post_excerpt'] 		= $_POST['form']['short'];
			$my_post['post_status'] 		= get_option("display_listing_status");
			$my_post['post_author'] 		= $user_ID;
			$my_post['post_category'] 		= $NewcatArray;
			$my_post['tags_input'] 			= $_POST['form']['tags'];
			$POSTID 						= wp_insert_post( $my_post );
 
			add_post_meta($POSTID, "hits", "0");
			if(!isset($_POST['form']['price'])){ add_post_meta($POSTID, "price", "0"); }else{ $_POST['form']['price'] = str_replace(",","",$_POST['form']['price']); } 
			add_post_meta($POSTID, "featured", "no");
			
			if(isset($_POST['form']['country']) && !is_numeric($_POST['form']['country'])){
				  add_post_meta($POSTID, "country", $_POST['form']['country']);	
			}
			
			if(isset($_POST['form']['state']) && !is_numeric($_POST['form']['state'])){
				  add_post_meta($POSTID, "state", $_POST['form']['state']);	
			}
						
			if(is_array($_POST['form']) ){
				foreach($_POST['form'] as $key => $val){
					if(!in_array($key,$DefaultFields)){
						add_post_meta($POSTID, $key, $val);			
					}	
				}	
			}

			if(is_array($_POST['custom']) ){
				foreach($_POST['custom'] as $in_array){
						add_post_meta($POSTID, $in_array['name'], $this->nl2br2($in_array['value']));				
				}	
			}

			if(strlen($uploaded_files) > 2 ){		
				$imgS = explode(",",$uploaded_files);
				add_post_meta($POSTID, 'image', $imgS[0]);
				add_post_meta($POSTID, 'images', $uploaded_files); 
			}
	
			if(isset($_POST['packageID'])){
			
					$PACKAGE_OPTIONS = get_option("packages"); 
					
					add_post_meta($POSTID, "packageID", $_POST['packageID'] );
			
					if(strlen($PACKAGE_OPTIONS[$_POST['packageID']]['expire']) > 0){
						add_post_meta($POSTID, "expires", $PACKAGE_OPTIONS[$_POST['packageID']]['expire']);		
					}
			
					if($PACKAGE_OPTIONS[$_POST['packageID']]['a5'] == 1){
						update_post_meta($POSTID, "featured", "yes");
					}	
	
					return $POSTID;
			
			}else{
	
				return $POSTID;
	
			}
		}		
	
	}

/*****************************************************************
	THIS FUNCTION IS USED TO CHECK IF THE OWNER OF THE LISTING
	IS THE ONE TRYING TO EDIT THE POST
*******************************************************************/
function authme($post_id, $user_id){
	
	global $wpdb; $userdata; 
		
	if(!is_numeric($post_id)){ return; }
 
 		$result = mysql_query("SELECT count($wpdb->posts.ID) AS total FROM $wpdb->posts WHERE $wpdb->posts.ID ='".$post_id."' AND $wpdb->posts.post_author ='".$user_id."' LIMIT 1", $wpdb->dbh) or die(mysql_error().' on line: '.__LINE__);
	
		$array = mysql_fetch_assoc($result);
		if ($array['total'] ==0) {
			die("no access");
	}

	return;
	
}
/*****************************************************************
	THIS FUNCTION IS USED TO GET THE CUSTOM FIELD VALUE
	FOR THE ITEM
*******************************************************************/
function GetListingCustom($postid, $key ){
	
		global $wpdb; $string = "";
	 
		$meta_values = get_post_meta($postid, $key, true);
 
		return $meta_values;
	
}
/*****************************************************************
	THIS FUNCTION IS USED TO DELETE A LISTING
*******************************************************************/
function Deletelisting($User_ID, $postid){

		global $wpdb; $userdata;
	 
		$this->authme($postid, $User_ID);
	
		$data = array();
	
		if(!is_numeric($postid)){ die("nice try!"); }
	
		wp_delete_post($postid);
	 
		return 1;
}

/*****************************************************************
	THIS FUNCTION IS USED TO GET THE CONTENTS OF THE POST DATA 
	USED WHEN EDITING A LISTING
*******************************************************************/
function Getlistingdata($id, $postid, $user_ID){
	
		global $wpdb; $userdata;
	
		$this->authme($postid, $user_ID);
	
		$data = array();
	
		if(!is_numeric($postid)){ die("nice try!"); }
	
		$post = get_post( $postid );
		$categories = get_the_category($postid);
	 
		$custom_fields = get_post_custom($postid);
	
		foreach ( $custom_fields as $key => $value ){
	
			$data[$key] =  $value[0];
	
		}

		$data['post_title'] 	=  $post->post_title;
		$data['post_excerpt'] 	=  $post->post_excerpt;
		$data['post_content'] 	=  $post->post_content;
		$data['cats'] 			=  $categories;
		return $data;
	
	}


 

	function ThisURL() {

		$s = empty($_SERVER["HTTPS"]) ? '' : ($_SERVER["HTTPS"] == "on") ? "s" : "";
		$protocol = "http".$s;
		$port = ($_SERVER["SERVER_PORT"] == "80") ? ""
			: (":".$_SERVER["SERVER_PORT"]);
		return $protocol."://".$_SERVER['SERVER_NAME'].$port.$_SERVER['REQUEST_URI'];
	}

/*****************************************************************
	THIS FUNCTION IS USED TO CREATE A RANDOM NUMBER FOR THE ORDER ID
*******************************************************************/

function RandomID($PasswordLenght = 10) {  
		$pass=""; 
		$salt = "0123456789123456789123456789123456789"; 
		srand((double)microtime()*1000000); 
		$i = 0; while ($i <= $PasswordLenght) {  $num = rand() % 33; $tmp = substr($salt, $num, 1); $pass = $pass . $tmp; $i++; }  
		return $pass; 
}

/*****************************************************************
	THIS FUNCTION IS USED TO UPDATE THE HIT COUNTER
*******************************************************************/

function UpdateHits($id=0, $current=0){

		global $wpdb;
		if(is_numeric($id)){  
			if($current == ""){ $current=0; }
			$current++;
			update_post_meta($id, 'hits', $current);
		}

}

/*****************************************************************
	THIS FUNCTION IS USED TO CHECK IF A KEY EXISTS, PRIMARLY USED
	DURING THE ADD ITEM PAGE FUNCTIONS
*******************************************************************/

function CheckExists($key,$value){

		global $wpdb;

		$SQL = "SELECT post_id FROM $wpdb->postmeta WHERE $wpdb->postmeta.meta_key='".PPTCLEAN($key)."' AND $wpdb->postmeta.meta_value LIKE '%".PPTCLEAN($value)."%' LIMIT 1";	
 
		$found = (array)$wpdb->get_results($SQL);
 
		if($found[0]->post_id != ""){ 
			return $found[0]->post_id;
		}else{
			return false;
		}

	}
 
 

	function selfURL() {
		$s = empty($_SERVER["HTTPS"]) ? '' : ($_SERVER["HTTPS"] == "on") ? "s" : "";
		$protocol = "http".$s;
		$port = ($_SERVER["SERVER_PORT"] == "80") ? ""
			: (":".$_SERVER["SERVER_PORT"]);
		return $protocol."://".$_SERVER['SERVER_NAME'].$port.$_SERVER['REQUEST_URI'];
	}


	function PageSelection($ThisPage="",$sValue = "guid"){
	
			global $wpdb;
	
			$STRING = "";
			$Pages = get_pages("parent=0");
			$Page_Count = count($Pages);	
				 
			foreach ($Pages as $Page) {		
	 
				$STRING.= '<option value="'.$Page->$sValue.'"';
				if($ThisPage == $Page->$sValue){ $STRING.=" selected"; }
				$STRING .= ">".$Page->post_title;
				$STRING .= '</option>';
	
				if($type ==0){
					$inner_pages = get_pages('child_of='.$Page->ID.'&sort_column=post_date&sort_order=desc');
					$inner_pages_count = count($inner_pages);
		
					if($inner_pages_count > 0){
						$STRING .= '<ul>';
						foreach($inner_pages as $inner_page){
			
							$STRING.= '<li><a href="'.get_page_link( $inner_page->ID ).'" title="'.$inner_page->post_title.'">';
							$STRING .= $inner_page->post_title;
							$STRING .= '</a></li>';
			
						}
						$STRING .= '</ul>';
					}
				}
			$STRING .= '</li>';
			}		
			
			echo  $STRING;	
	}

  

	function AffiliateLink($link, $id=""){

	global $wpdb;
 
		if(get_option("display_linkcloak") =="yes" && $id > 0){	
		
			$ll = get_option("tc_linkcloak");
			if(strlen($ll) < 2){
			$ll = $GLOBALS['template_url']."/_link.php";
			}
			
			return $ll."?link=".$id; 
		}
	 
 	 
 		$pos = stripos($link, "affiliatefuture");
		if ($pos !== false) {
			$link = str_replace('YOURUSERID',get_option("affiliates_2_ID"),$link);
			return $link.get_option("affiliates_2_TRACK");
		}

 		$pos = stripos($link, "linkshare");
		if ($pos !== false) {
			$link = str_replace('YOURUSERID',get_option("affiliates_3_ID"),$link);
			return $link.get_option("affiliates_3_TRACK");
		}
		
 		$pos = stripos($link, "linksynergy");
		if ($pos !== false) {
			$link = str_replace('YOURUSERID',get_option("affiliates_3_ID"),$link);
			return $link.get_option("affiliates_3_TRACK");
		}		

  		$pos = stripos($link, "regnow");
		if ($pos !== false) {
			$link = str_replace('YOURUSERID',get_option("affiliates_4_ID"),$link);
			return $link.get_option("affiliates_4_TRACK");
		}

		$pos = stripos($link, "kqzyfj");
		if ($pos !== false) {
			$link = str_replace('YOURUSERID',get_option("affiliates_5_ID"),$link);
			return $link.get_option("affiliates_5_TRACK");
		}

		$pos = stripos($link, "dpbolvw");
		if ($pos !== false) {
			$link = str_replace('YOURUSERID',get_option("affiliates_5_ID"),$link);
			return $link.get_option("affiliates_5_TRACK");
		}
		
		$pos = stripos($link, "jdoqocy");
		if ($pos !== false) {
			$link = str_replace('YOURUSERID',get_option("affiliates_5_ID"),$link);
			return $link.get_option("affiliates_5_TRACK");
		}
		
		$pos = stripos($link, "anrdoezrs");
		if ($pos !== false) {
			$link = str_replace('YOURUSERID',get_option("affiliates_5_ID"),$link);
			return $link.get_option("affiliates_5_TRACK");
		}
		
		$pos = stripos($link, "tkqlhce");
		if ($pos !== false) {
			$link = str_replace('YOURUSERID',get_option("affiliates_5_ID"),$link);
			return $link.get_option("affiliates_5_TRACK");
		}		
		$pos = stripos($link, "jdoqocy");
		if ($pos !== false) {
			$link = str_replace('YOURUSERID',get_option("affiliates_5_ID"),$link);
			return $link.get_option("affiliates_5_TRACK");
		}

		$pos = stripos($link, "tkqlhce");
		if ($pos !== false) {
			$link = str_replace('YOURUSERID',get_option("affiliates_5_ID"),$link);
			return $link.get_option("affiliates_5_TRACK");
		}

		$pos = stripos($link, "anrdoezrs");
		if ($pos !== false) {
			$link = str_replace('YOURUSERID',get_option("affiliates_5_ID"),$link);
			return $link.get_option("affiliates_5_TRACK");
		}

  		$pos = stripos($link, "webgains");
		if ($pos !== false) {
			$link = str_replace('YOURUSERID',get_option("affiliates_6_ID"),$link);
			return $link.get_option("affiliates_6_TRACK");
		}	

		$pos = stripos($link, "clickbank");
		if ($pos !== false) {
			$link = str_replace('YOURUSERID',get_option("affiliates_7_ID"),$link);
			return $link.get_option("affiliates_7_TRACK");
		}

  		$pos = stripos($link, "tradedoubler");
		if ($pos !== false) {
			$link = str_replace('YOURUSERID',get_option("affiliates_8_ID"),$link);
			return $link.get_option("affiliates_8_TRACK");
		}	

		$pos = stripos($link, "bridaluxe");
		if ($pos !== false) {
			$link = str_replace('YOURUSERID',get_option("affiliates_9_ID"),$link);
			return $link.get_option("affiliates_9_TRACK");
		}
 
		$pos = stripos($link, "linkconnector");
		if ($pos !== false) {
			$link = str_replace('YOURUSERID',get_option("affiliates_10_ID"),$link);
			return $link.get_option("affiliates_10_TRACK");
		}

		$pos = stripos($link, "netshops");
		if ($pos !== false) {
			$link = str_replace('YOURUSERID',get_option("affiliates_11_ID"),$link);
			return $link.get_option("affiliates_11_TRACK");
		}

		$pos = stripos($link, "buy.at");
		if ($pos !== false) {
			$link = str_replace('YOURUSERID',get_option("affiliates_12_ID"),$link);
			return $link.get_option("affiliates_12_TRACK");
		}

		$pos = stripos($link, "pepperjam");
		if ($pos !== false) {
			$link = str_replace('YOURUSERID',get_option("affiliates_13_ID"),$link);
			return $link.get_option("affiliates_13_TRACK");
		}

		$pos = stripos($link, "pntrs");
		if ($pos !== false) {
			$link = str_replace('YOURUSERID',get_option("affiliates_13_ID"),$link);
			return $link.get_option("affiliates_13_TRACK");
		}


		$pos = stripos($link, "google");
		if ($pos !== false) {
			$link = str_replace('YOURUSERID',get_option("affiliates_14_ID"),$link);
			return $link.get_option("affiliates_14_TRACK");
		}
		
		$pos = stripos($link, "doubleclick");
		if ($pos !== false) {
			$link = str_replace('YOURUSERID',get_option("affiliates_14_ID"),$link);
			return $link.get_option("affiliates_14_TRACK");
		}

		$pos = stripos($link, "clickserve");
		if ($pos !== false) {
			$link = str_replace('YOURUSERID',get_option("affiliates_14_ID"),$link);
			return $link.get_option("affiliates_14_TRACK");
		}

		$pos = stripos($link, "affiliatewindow");
		if ($pos !== false) {
			$link = str_replace('YOURUSERID',get_option("affiliates_15_ID"),$link);
			return $link.get_option("affiliates_15_TRACK");
		}

		$pos = stripos($link, "awin1");
		if ($pos !== false) {
			$link = str_replace('YOURUSERID',get_option("affiliates_15_ID"),$link);
			return $link.get_option("affiliates_15_TRACK");
		}

		$pos = stripos($link, "commissionmonster");
		if ($pos !== false) {
			$link = str_replace('YOURUSERID',get_option("affiliates_16_ID"),$link);
			return $link.get_option("affiliates_16_TRACK");
		}

		$pos = stripos($link, "markethealth");
		if ($pos !== false) {
			$link = str_replace('YOURUSERID',get_option("affiliates_17_ID"),$link);
			return $link.get_option("affiliates_17_TRACK");
		}

		$pos = stripos($link, "affilinet");
		if ($pos !== false) {
			$link = str_replace('YOURUSERID',get_option("affiliates_18_ID"),$link);
			return $link.get_option("affiliates_18_TRACK");
		}

		$pos = stripos($link, "onenetworkdirect");
		if ($pos !== false) {
			$link = str_replace('YOURUSERID',get_option("affiliates_19_ID"),$link);
			return $link.get_option("affiliates_19_TRACK");
		}

		$pos = stripos($link, "amazon");
		if ($pos !== false) {
			$link = str_replace('YOURUSERID',"?tag=".get_option("affiliates_20_ID"),$link);
			return $link.get_option("affiliates_20_TRACK");
		}


		
		$pos = stripos($link, "shareasale");
		if ($pos !== false) {
			$link = str_replace('YOURUSERID',get_option("affiliates_1_ID"),$link);
			return $link.get_option("affiliates_1_TRACK");
		}		
 
	return $link;	
	
	}


	function AmazonSavedSearch(){

		global $wpdb;
	
		$ASS 						= array();
		$ASS 						= get_option("AmazonSavedSearch_Data");
		$ASS_TOTAL 					= get_option("AmazonSavedSearch_Total");

		if($ASS_TOTAL == "" || !is_numeric($ASS_TOTAL) || $ASS_TOTAL < 0){$ASS_TOTAL = 0;	}else{	$ASS_TOTAL++;	}
 
		$ASS[$ASS_TOTAL]['name'] 	= $_POST['schedule']['name'];
		$ASS[$ASS_TOTAL]['time'] 	= $_POST['schedule']['time'];
		$ASS[$ASS_TOTAL]['total'] 	= 0;
		$ASS[$ASS_TOTAL]['last'] 	= "Never";
		$ASS[$ASS_TOTAL]['status'] 	= "Running";
		$ASS[$ASS_TOTAL]['cat'] 	= $_POST['cat'];

		foreach($_POST['amazon'] as $key => $val){	
			$ASS[$ASS_TOTAL][$key] 	= $val; 	
		}		

		update_option("AmazonSavedSearch_Total",$ASS_TOTAL);
		update_option("AmazonSavedSearch_Data",$ASS);		
	
	}

	function AmazonRunSearch($RunID=0){
	
			global $wpdb, $PPTImport;
		 	$mA 						= array();
			$ASS 						= get_option("AmazonSavedSearch_Data");
			$ASS_TOTAL_NEW 				= 0;
		
			foreach($ASS as $inArray){
			 
				if($ASS_TOTAL_NEW	 == $RunID){
				$mA = array(0 => $inArray);				 
				$num = $PPTImport->amazon_dreepfeed($inArray['time'],$mA);
				 
				}				
			 
			$ASS_TOTAL_NEW++;
			}
	
	}

	function AmazonDeleteSearch($id=0){

		global $wpdb;
	
		$ASS_NEW 					= array();
		$ASS 						= get_option("AmazonSavedSearch_Data");
		$ASS_TOTAL 					= get_option("AmazonSavedSearch_Total");
		$ASS_TOTAL_NEW 				= 0;

		delete_option("AmazonSavedSearch_Data");
		delete_option("AmazonSavedSearch_Total");
 
		foreach($ASS as $inArray){		
		if($ASS_TOTAL_NEW != $id){
			foreach($inArray as $key => $val){		
				$ASS_NEW[$ASS_TOTAL_NEW][$key] 	= $val; 		
			}
		}
		$ASS_TOTAL_NEW++;
		}

		update_option("AmazonSavedSearch_Data",$ASS_NEW);
		update_option("AmazonSavedSearch_Total",count($ASS_NEW));
	
	}



/************ SHRINK THE WEB FUNCTIONALITY ******************/

	function SaveImage($url, $args=""){

		global $wpdb;

		$targetFile = str_replace("http://","",$url);
		$targetFile = str_replace("www.","",$targetFile);
		$targetFile = str_replace(" ","",$targetFile);
		$targetChecker = explode("/",$targetFile);
		if( get_option("stw_3")  == "1"){
		$targetFile = str_replace("http://","",$url);
		}else{
		$targetFile = $targetChecker[0];
		}
	 
		$bad_sizes 		= array('15919','14941','0','1888','842');
		
		$IMAGESTR = get_option("imagestorage_path").$targetFile.".jpg";
	 
		if(@file_exists($IMAGESTR)){ // && get_option("image_preview_storage") != "no"
		 
			if(in_array(@filesize($IMAGESTR),$bad_sizes)){
			
				@unlink($IMAGESTR);
			 
			 }
		
			return get_option("imagestorage_link").$targetFile.".jpg?f=".@filesize($IMAGESTR);
		
		}else{
		
		if($_SERVER['HTTP_HOST'] == "localhost"){
		
			return $this->ImageCheck("localhost.gif");
		
		}

			$query_string ="";
			$query_string.="&ip=".$_SERVER['SERVER_ADDR']; 
			$query_string.="&host=".$_SERVER['HTTP_HOST'];	
			$query_string.="&license=".get_option("license_key");
			$query_string.="&v=".PREMIUMPRESS_VERSION;
			
			if(isset($args['custom'])){
			
				$customSize = false;
				$target = "http://images.shrinktheweb.com/xino.php?embed=1&STWAccessKeyId=".$args['key'];
				
				if( get_option("stw_1")  == "1"){
					$target .="&stwinside=1";
				}
				if( get_option("stw_2")  == "1"){
					$target .="&stwredo=1";
				}
				if( get_option("stw_3")  == "1"){
				 
					$customSize=true;
					$target .="&stwfull=1";					
					$target .="&stwxmax=200";					
					
				}else{
				
					if(strlen(get_option("stw_4")) > 0){
						$customSize=true;
						$target .="&stwxmax=".get_option("stw_4");			
					}
				}			
				
				
				
				if(strlen(get_option("stw_5")) > 0){
					$target .="&stwdelay=".get_option("stw_5");			
				}			
	
				if(strlen(get_option("stw_6")) > 0){
					$target .="&stwq=".get_option("stw_6");			
				}
							
				if(!$customSize){ $target .= "&stwsize=xlg&Size=xlg"; }
				
				$target .= "&stwUrl=http://www.".$targetFile;
			
				
			}else{
			
				$target = "http://www.directorypress.net/api.php?url=".$url."".$query_string;
			}
			
			if($GLOBALS['premiumpress']['thumbresize'] != "off"){
 
				$response = wp_remote_get( $target );
							
				if( is_wp_error( $response ) ) {
				
				   //echo 'Something went wrong!';
				   
				} else {
				
					if(strlen($response['body']) > 10){ 
					
						$ch = curl_init ($target);
						curl_setopt($ch, CURLOPT_HEADER, 0);
						curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);
						curl_setopt($ch, CURLOPT_BINARYTRANSFER,1);
						$rawdata=curl_exec ($ch);
						curl_close ($ch);		
				
						$fp = fopen(get_option("imagestorage_path").$targetFile.".jpg",'w');
						fwrite($fp, $rawdata);
						fclose($fp);
					
						$fp = @fopen(get_option("imagestorage_path").$targetFile.".jpg",'w');
						@fwrite($fp, $response['body']);
						@fclose($fp);
					
					}
				}
			
			
			}
 
			return $target;


		}

	}



	function CategoryExtras($cat_id,$type="text",$return=0){
	
		global $wpdb;
		
		if($type == "text"){

			return stripslashes(get_option("cat_extra_text_".$cat_id));	

		}elseif($type == "image"){

			$img = $this->ImageCheck(get_option("cat_extra_image_".$cat_id),"full");

			if(strlen(get_option("cat_extra_image_".$cat_id)) > 0){
				if($return ==1){
					return $img;
				}else{
					return "<img src='".$img."' id='StoreImage'>";
				}				

			}
		}		
	
	}

	function FeaturedCategories(){

		global $wpdb; $STRING = "";
 
		$SAVED_DISPLAY = get_option("featured_stores");

			if(is_array($SAVED_DISPLAY)){
				$SHOWRESULTS = $this->multisort( $SAVED_DISPLAY , array('ORDER') );
			}else{
				$SHOWRESULTS = array();
			} 		

			foreach($SHOWRESULTS as $ThisCat){  if( isset($ThisCat['ID']) && $ThisCat['ID'] > 0 ){ 
 
				$catBits = get_category($ThisCat['ID'],false);

				if(!empty($catBits)){
				$storeimage = $this->CategoryExtras($ThisCat['ID'],$type="image",1);
			
				$STRING .= "<li>";
				$STRING .= "<a href='".get_category_link( $ThisCat['ID'] )."' title='".$catBits->cat_name."' style='text-decoration:none;'";

				if(isset($GLOBALS['premiumpress']['analytics_tracking']) && $GLOBALS['premiumpress']['analytics_tracking'] =="yes"){
				$STRING .= "onclick=\"pageTracker._trackEvent('STORE CLICK', 'IMAGE CLICK', '".$catBits->cat_name."');\"";
				}
				$STRING .= ">";

				$STRING .= "<div style='width:150px; height:60px; overflow:hidden;'>";
				if($storeimage != ""){ 
					$STRING .= "<img src='".$storeimage."' style='bordr:0px; text-decoration:none;' />";
				}
				$STRING .= "</div>";				
				
				$STRING .= "</a><div style='clear:both;'></div>
				<a href='".get_category_link( $catBits->term_id )."' title='".$catBits->cat_name."' style='font-size:12px;'";
				if(isset($GLOBALS['premiumpress']['analytics_tracking']) && $GLOBALS['premiumpress']['analytics_tracking'] =="yes"){
				$STRING .= "onclick=\"pageTracker._trackEvent('STORE CLICK', 'TEXT CLICK', '".$catBits->cat_name."');\"";
				}
				$STRING .= ">";
				$STRING .= $catBits->cat_name." (".$catBits->category_count.")";
				$STRING .= "</a>";
				$STRING .= "</li>";
				}
			
			} }

 
 
		return $STRING; 
	 
	}

 
	function CheckExpired($post_id,$POSTDATE=""){ 
	
	$dateformat = false; $post_expires = "";
	
	if($GLOBALS['premiumpress']['feature_expiry'] == ""){ $GLOBALS['premiumpress']['feature_expiry'] = get_option("feature_expiry"); }
	if($GLOBALS['premiumpress']['feature_expiry_do'] == ""){ $GLOBALS['premiumpress']['feature_expiry_do'] = get_option("feature_expiry_do"); }
	
		if($GLOBALS['premiumpress']['feature_expiry'] != "yes"){ return; }

		global $wpdb;

		if(strtolower(constant('PREMIUMPRESS_SYSTEM')) == "couponpress"){ 
			$post_expires = get_post_meta($post_id, "pexpires", true);
			$dateformat = true;
		}
		
		// FALLBACK ONTO THE NUMERIC EXPIRY DATE
		if($post_expires == ""){		
		
			$post_expires = get_post_meta($post_id, "expires", true);
		}
		 
		if($post_expires ==""){
				return false; // invalid date
		}		
		
		// IF ITS A NUMBERIC (NUMBER OF DAYS VALUE) 
		if(is_numeric($post_expires) || $dateformat==true ){
		
			// DATE FORMAT IS FOR COUPONPRESS COUPONS
			if($dateformat){
			$AHHH = date('Y-m-d h:i:s',strtotime(date("Y-m-d h:i:s", strtotime($post_expires) )));
			}else{
			$AHHH = date('Y-m-d h:i:s',strtotime(date("Y-m-d h:i:s", strtotime($POSTDATE )) . " +".$post_expires." days"));
			}
		 	
			//die($AHHH."--".date("Y-m-d h:i:s", strtotime($post_expires) ));
		
			// check if todays date is greater than the post date + package lenght
			if( date('Y-m-d h:i:s') > $AHHH ){	 			
			
				$my_post 				= array();
				$my_post['ID'] 			= $post_id;
				
				 
				
				if(!isset($GLOBALS['premiumpress']['feature_expiry_do']) || strlen($GLOBALS['premiumpress']['feature_expiry_do']) < 1){
				$GLOBALS['premiumpress']['feature_expiry_do'] = get_option('feature_expiry_do');
				}
				
				
				
				switch($GLOBALS['premiumpress']['feature_expiry_do']){							
				
					case "draft":{  	$my_post['post_status'] = "draft"; } break;
					case "delete":{  	wp_delete_post( $post_id, true ); return true; } break;					
					case "pak1":{  	update_post_meta($post_id, "packageID", "1"); } break;
					case "pak2":{  	update_post_meta($post_id, "packageID", "2"); } break;
					case "pak3":{  	update_post_meta($post_id, "packageID", "3"); } break;
					case "pak4":{  	update_post_meta($post_id, "packageID", "4"); } break;
					case "pak5":{  	update_post_meta($post_id, "packageID", "5"); } break;
					case "pak6":{  	update_post_meta($post_id, "packageID", "6"); } break;
					case "pak7":{  	update_post_meta($post_id, "packageID", "7"); } break;
					case "pak8":{  	update_post_meta($post_id, "packageID", "8"); } break;					
					default: { 			 $my_post['post_category'] 	= array($GLOBALS['premiumpress']['feature_expiry_do']); } break;			
				
				} 
				 
				wp_update_post( $my_post );
				
				update_post_meta($post_id, "expires", "");
				
				return true;
					
			}	
			
			return false; // not expired	
		}
		
		
		
		
		
		
		// IF ITS A DATE VALUE
		$splitDate = explode(" ",$post_expires);
		$EXPIRYDATE = $splitDate[0];
		
		if(strlen($EXPIRYDATE) != "10" ){ return false; } // incorrect string lenght
 
		if ( strtotime(date("Y-m-d")) > strtotime($EXPIRYDATE) ) {

			if($GLOBALS['premiumpress']['feature_expiry'] =="yes"){ 
			
				$my_post 				= array();
				$my_post['ID'] 			= $post_id;
			
				switch($GLOBALS['premiumpress']['feature_expiry_do']){							
				
					case "draft":{  	$my_post['post_status'] = "draft"; } break;
					case "delete":{  	wp_delete_post( $post_id, true ); return true; } break;					
					case "pak1":{  	update_post_meta($post_id, "packageID", "1"); } break;
					case "pak2":{  	update_post_meta($post_id, "packageID", "2"); } break;
					case "pak3":{  	update_post_meta($post_id, "packageID", "3"); } break;
					case "pak4":{  	update_post_meta($post_id, "packageID", "4"); } break;
					case "pak5":{  	update_post_meta($post_id, "packageID", "5"); } break;
					case "pak6":{  	update_post_meta($post_id, "packageID", "6"); } break;
					case "pak7":{  	update_post_meta($post_id, "packageID", "7"); } break;
					case "pak8":{  	update_post_meta($post_id, "packageID", "8"); } break;					
					default: { 			 $my_post['post_category'] 	= array($GLOBALS['premiumpress']['feature_expiry_do']); } break;		
				
				}
			
				wp_update_post( $my_post );
				
				update_post_meta($post_id, "expires", "");

				return true;
			}	 

		}else{
		
			return false; // not expired
		
		}
		 
	
	}



	function CheckPrune($post){
	
		global $wpdb;
	
		if($GLOBALS['premiumpress']['post_prun'] == "yes" && is_numeric($GLOBALS['premiumpress']['prun_period']) ){
		
		// check if todays date is greater than the post date + package lenght
		if( date('Y-m-d h:i:s') > date('Y-m-d h:i:s',strtotime(date("Y-m-d h:i:s", strtotime($post->post_date)) . " +".$GLOBALS['premiumpress']['prun_period']." days")) ){
	 
			 
				$my_post 				= array();
				$my_post['ID'] 			= $post->ID;
				
				switch($GLOBALS['premiumpress']['prun_status']){							
				
					case "draft":{  $my_post['post_status'] = "draft"; } break;
					case "delete":{ wp_delete_post( $post->ID, true ); return true; } break;					
					case "pak1":{  	update_post_meta($post->ID, "packageID", "1"); } break;
					case "pak2":{  	update_post_meta($post->ID, "packageID", "2"); } break;
					case "pak3":{  	update_post_meta($post->ID, "packageID", "3"); } break;
					case "pak4":{  	update_post_meta($post->ID, "packageID", "4"); } break;
					case "pak5":{  	update_post_meta($post->ID, "packageID", "5"); } break;
					case "pak6":{  	update_post_meta($post->ID, "packageID", "6"); } break;
					case "pak7":{  	update_post_meta($post->ID, "packageID", "7"); } break;
					case "pak8":{  	update_post_meta($post->ID, "packageID", "8"); } break;
					
					default: { 	$my_post['post_category'] 	= array($GLOBALS['premiumpress']['prun_status']); } break;			
				
				} 
				
				$re = wp_update_post( $my_post );
				
				//update_post_meta($post_id, "pruned", date('d-m-Y'));
 
					
			}		
		
		}	
	
	
	}
	
	
	function CheckLink($post){
	
		global $wpdb;
			
		$link 				= get_post_meta($post->ID, "link", true);
		if($link == ""){		
			$link 				= get_post_meta($post->ID, "customurl", true);
			if($link == ""){
				$link  	= get_post_meta($post->ID, "url", true);
			}
		
		}
		
		if($link  == ""){ return false; }
		 
		$pos = strpos($link , 'http://'); $pos1 = strpos($link , 'https');
		
		if ($pos === false && $pos1 === false && $link  != "") {		$link  = "http://".$link ;		} 
		
		// LINK CLOAKING
		if($GLOBALS['premiumpress']['linkcloak'] =="yes"){		
			$link = $GLOBALS['premiumpress']['linkcloak_url']."?link=".$post->ID; 
		}	
			
		return $link;
		
	
	}











// CURRENCY OPTIONS FOR MULTIPLE CURRENCY VALUES

	function CURRENCYEXCHANGE($CurrencyCode){

	$CC = array();

	$CurrencyCode = strip_tags($CurrencyCode);
	
	// CHECK THE DEFAULT ONE FIRST
	
	if($CurrencyCode == get_option("currency_code")){
	
			$CC['caption'] = get_option("currency_caption");
			$CC['code'] = get_option("currency_code");
			$CC['symbol'] = get_option("currency_symbol");
			$CC['value'] = get_option("currency_value");
			
			return $CC;
			
	}
 
	for($i=1; $i < 6; $i++){
	 	
		if( $CurrencyCode == get_option("currency_code_".$i)){		
		
			$CC['caption'] = get_option("currency_caption_".$i);
			$CC['code'] = get_option("currency_code_".$i);
			$CC['symbol'] = get_option("currency_symbol_".$i);
			$CC['value'] = get_option("currency_value_".$i);

		}
	
	}	
	
	return $CC;

	}
	
	
	
	
	
	
	
	function editlistingimages($post_id){
	
		global $wpdb; $userdata; $string = ""; $imagePath= "";
	 
		$image = get_post_meta($post_id, "image", true); 
		$image_s = get_post_meta($post_id, "images", true);
		
	
		$pos = strpos($GLOBALS['premiumpress']['submit_url'], '?'); 
		if ($pos === false) {
			$elink = $GLOBALS['premiumpress']['submit_url']."?";			
		} else {
			 $elink = $GLOBALS['premiumpress']['submit_url']."&";			 
		} 
		
		$imgBits = explode("/",get_permalink());	
		$tt = count($imgBits)-2; $it=0;
		
		while($tt > 0){  
			$imagePath .= $imgBits[$it]."/";
			$tt--;$it++;		 
		}
 
	   
		$pics = explode(",", $image_s);
	
		if(is_array($pics)){
			foreach($pics as $pic) {
				if(strlen($pic) > 2){
				$string .="<li class='First'>";
				
				switch(substr($pic,-3)){
				
					case "pdf": {
					
					$pic1 = "".$imagePath."wp-content/themes/".strtolower(PREMIUMPRESS_SYSTEM)."/PPT/img/icon-pdf.gif";
					
					} break;
					
					case "": {
					
					} break;	
					
					default: {
					$pic1 = $pic;
					
					}			
				
				}
				
				$string .="<a href='".$this->ImageCheck($pic)."' rel='gallery' target='_blank'>				
				<img src='".$this->ImageCheck($pic1)."'";
				
				if($image == $pic){  $string .='style="border:2px solid red;"'; }
				$string .="/>
				</a>				
				
				<br /> 
				
				<a href='".$elink."eid=".$post_id."&pid=".$pic."'>
				<img src='".$imagePath."wp-content/themes/".strtolower(PREMIUMPRESS_SYSTEM)."/images/premiumpress/led-ico/cross.png' alt='delete' style='width:16px; height:16px;border:0px; float:left; margin-right:20px;' />
				</a>


				<a href='".$elink."eid=".$post_id."&pid=".$pic."&display=1'>
				<img src='".$imagePath."wp-content/themes/".strtolower(PREMIUMPRESS_SYSTEM)."/images/premiumpress/led-ico/monitor.png' alt='display' style='width:16px; height:16px;border:0px;float:left;' />
				</a>
								
 
				
				
				  </li>";
			} }
		}else{
			return "<li>".$GLOBALS['_LANG']['_err13']."</li>";
		}
	
		return $string;
	
	
	}

 
	function DownloadFile($itemID, $ignore_credit=0){

	global $wpdb; global $userdata; get_currentuserinfo();
 
	$price = get_post_meta($itemID, "price", true);
 	$file = get_post_meta($itemID, "file", true);
	$fileType = get_post_meta($itemID, "file_type", true);

	// GET THE FILE STORAGE PATH
	$server_path = get_option("download_server_path");
	if($server_path ==""){
	
		$server_path = get_option("imagestorage_path");
		if($server_path ==""){	
			die("<h1>Download Server Path Error</h1><p>The download server paths have not been setup via the admin area. Please contact the server admin.</p>");
		}
	}

	// USER MUST BE LOGGED IN TO DOWNLOAD
	if($ignore_credit ==0){ if(!isset($userdata->ID) || $userdata->ID ==""){
		header("location: wp-login.php?action=login");exit();
	} }
 
  
 	if($ignore_credit ==1 || $fileType == "free"){ $price=0; } // used for 
 
	// MAKE SURE WE HAVE ENOUGH CREDITS
	if( ( $userdata->aim >= $price ) || ( $price == 0 ) ){
 
		if($file ==""){
	
			die("<h1>Download Link Missing for item ".$itemID.". Please contact support.</h1>");
		
		}else{ 
	 
			$file_path = $server_path . $file;

			if(file_exists($file_path)){
			
				// SETUP COOKIE FOR DOWNLOAD WITHOUT REPURCHASE
				setcookie("ItemDownload".$itemID, $itemID."-".$userdata->ID, time()+3600*100);

				// REMOVE DOWNLOAD CREDITS	  
				$wpdb->query("UPDATE $wpdb->usermeta SET meta_value=meta_value-".round($price,1)." WHERE meta_key='aim' AND user_id=('".$userdata->ID."') LIMIT 1");
			 

				$sub = substr($file_path,-3);
				$file_size =@filesize($file_path);			
				header('Last-Modified: '.date('r')); 
				header('Content-Description: File Transfer'); 
				header('Content-Type: '.$this->returnMIMEType($sub).'');
				header("Content-disposition: attachment; filename=".$file."");
				header("Content-Length: ".$file_size."");
				ob_clean();
				flush();
				readfile($file_path);
				exit;

			}else{
				die("<h1> Download File Doesnt Exist</h1>".$file_path);
			}
		
		}

	}else{
	
		die("<h1>Insufficent Credits Remaining</h1>");

	}

	return $ReturnArray;
 
	
	}
	
	
 function returnMIMEType($ext)
    {
 
        switch(strtolower($ext))
        {
            case "js" :
                return "application/x-javascript";

            case "json" :
                return "application/json";

            case "jpg" :
            case "jpeg" :
            case "jpe" :
                return "image/jpg";

            case "png" :
            case "gif" :
            case "bmp" :
            case "tiff" :
                return "image/".strtolower($fileSuffix[1]);

            case "css" :
                return "text/css";

            case "xml" :
                return "application/xml";

            case "doc" :
            case "docx" :
                return "application/msword";

            case "xls" :
            case "xlt" :
            case "xlm" :
            case "xld" :
            case "xla" :
            case "xlc" :
            case "xlw" :
            case "xll" :
                return "application/vnd.ms-excel";

            case "ppt" :
            case "pps" :
                return "application/vnd.ms-powerpoint";

            case "rtf" :
                return "application/rtf";

            case "pdf" :
                return "application/pdf";

            case "html" :
            case "htm" :
            case "php" :
                return "text/html";

            case "txt" :
                return "text/plain";

            case "mpeg" :
            case "mpg" :
            case "mpe" :
                return "video/mpeg";

            case "mp3" :
                return "audio/mpeg3";

            case "wav" :
                return "audio/wav";

            case "aiff" :
            case "aif" :
                return "audio/aiff";

            case "avi" :
                return "video/msvideo";

            case "wmv" :
                return "video/x-ms-wmv";

            case "mov" :
                return "video/quicktime";

            case "zip" :
                return "application/zip";

            case "tar" :
                return "application/x-tar";

            case "swf" :
                return "application/x-shockwave-flash";

            default :
            return "application/octet-stream";
        }
    }
	
}

class ResizeImage extends PremiumPressTheme {
   
   var $image;
   var $image_type;
 
   function load($filename) {
      $image_info = getimagesize($filename);
      $this->image_type = $image_info[2];
      if( $this->image_type == IMAGETYPE_JPEG ) {
         $this->image = imagecreatefromjpeg($filename);
      } elseif( $this->image_type == IMAGETYPE_GIF ) {
         $this->image = imagecreatefromgif($filename);
      } elseif( $this->image_type == IMAGETYPE_PNG ) {
         $this->image = imagecreatefrompng($filename);
      }
   }
   function save($filename, $image_type=IMAGETYPE_JPEG, $compression=75, $permissions=null) {
      if( $image_type == IMAGETYPE_JPEG ) {
         imagejpeg($this->image,$filename,$compression);
      } elseif( $image_type == IMAGETYPE_GIF ) {
         imagegif($this->image,$filename);         
      } elseif( $image_type == IMAGETYPE_PNG ) {
         imagepng($this->image,$filename);
      }   
      if( $permissions != null) {
         chmod($filename,$permissions);
      }
   }
   function output($image_type=IMAGETYPE_JPEG) {
      if( $image_type == IMAGETYPE_JPEG ) {
         imagejpeg($this->image);
      } elseif( $image_type == IMAGETYPE_GIF ) {
         imagegif($this->image);         
      } elseif( $image_type == IMAGETYPE_PNG ) {
         imagepng($this->image);
      }   
   }
   function getWidth() {
      return imagesx($this->image);
   }
   function getHeight() {
      return imagesy($this->image);
   }
   function resizeToHeight($height) {
      $ratio = $height / $this->getHeight();
      $width = $this->getWidth() * $ratio;
      $this->resize($width,$height);
   }
   function resizeToWidth($width) {
      $ratio = $width / $this->getWidth();
      $height = $this->getheight() * $ratio;
      $this->resize($width,$height);
   }
   function scale($scale) {
      $width = $this->getWidth() * $scale/100;
      $height = $this->getheight() * $scale/100; 
      $this->resize($width,$height);
   }
   function resize($width,$height) {
      $new_image = imagecreatetruecolor($width, $height);
      imagecopyresampled($new_image, $this->image, 0, 0, 0, 0, $width, $height, $this->getWidth(), $this->getHeight());
      $this->image = $new_image;   
   }      
}

/************************ AMAZON PRODUCT IMPORT API *************************/

    class AmazonProductAPI
    {
 
       
        /**
         * Check if the xml received from Amazon is valid
         * 
         * @param mixed $response xml response to check
         * @return bool false if the xml is invalid
         * @return mixed the xml response if it is valid
         * @return exception if we could not connect to Amazon
         */
        private function verifyXmlResponse($response)
        {
            if ($response === False)
            {
                throw new Exception("Could not connect to Amazon");
            }
            else
            {
 
				if (isset($response->Items->Item->ItemAttributes->Title))
                {
                    return ($response);
                
                }elseif (isset($response->Cart))
                {
                    return ($response);
                }
				elseif(isset($response->Items->Request->Errors->Error->Message)){
				throw new Exception("<h1>There was an error but don't panic..</h1><p>".$response->Items->Request->Errors->Error->Message[0]."</p>");
				}
                else
                {
                    throw new Exception("<h1>We did not find any matches for your request</h1>");
                }
            }
        }
        
        
        /**
         * Query Amazon with the issued parameters
         * 
         * @param array $parameters parameters to query around
         * @return simpleXmlObject xml query response
         */
        private function queryAmazon($parameters, $country="com")
        {
            return aws_signed_request($country, $parameters);
        }
        
        
        /**
         * Return details of products searched by various types
         * 
         * @param string $search search term
         * @param string $category search category         
         * @param string $searchType type of search
         * @return mixed simpleXML object
         */
        public function searchProducts($search, $category, $values)
        { 
		
		if(strlen($values['minprice']) > 1){
		$values['minprice'].="00";
		}
		
		if(strlen($values['maxprice']) > 1){
		$values['maxprice'].="00";
		}
 
		if($category =="All"){
		$parameters = array(
		"Operation"  	=> "ItemSearch",
		"Keywords" 		=> $search,
		"SearchIndex"   => $category,
		"ResponseGroup" => "ItemAttributes,Offers,Images,EditorialReview,Reviews",
		"MinimumPrice" 	=> $values['minprice'],
		"MaximumPrice" 	=> $values['maxprice'],
		"ItemPage" 		=> $values['start_page'],
		"Brand"	 		=> $values['brand'],		
		"Condition" 	=> $values['condition'], 
		//"Sort" 			=> $values['Sort'],
		"MerchantId"	=> $values['merchantid']);
		}else{
		$parameters = array(
		"Operation"  	=> "ItemSearch",
		"Title" 		=> $search,
		"SearchIndex"   => $category,
		"ResponseGroup" => "ItemAttributes,Offers,Images,EditorialReview,Reviews",
		"MinimumPrice" 	=> $values['minprice'],
		"MaximumPrice" 	=> $values['maxprice'],
		"ItemPage" 		=> $values['start_page'],
		"BrowseNode"	=> $values['node'],
		"Brand"	 		=> $values['brand'],
		"Condition" 	=> $values['condition'],
		"Sort" 			=> $values['Sort'],
		"MerchantId"	=> $values['merchantid']);
		}
		
		
		
		//die(print_r($parameters));
		 
             
            $xml_response = $this->queryAmazon($parameters, $values['country']);
            
            return $this->verifyXmlResponse($xml_response);

        }
        
        
        /**
         * Return details of a product searched by UPC
         * 
         * @param int $upc_code UPC code of the product to search
         * @param string $product_type type of the product
         * @return mixed simpleXML object
         */
        public function getItemByUpc($upc_code, $product_type)
        {
            $parameters = array("Operation"     => "ItemLookup",
                                "ItemId"        => $upc_code,
                                "SearchIndex"   => $product_type,
                                "IdType"        => "UPC",
                                "ResponseGroup" => "Medium");
                                
            $xml_response = $this->queryAmazon($parameters);
            
            return $this->verifyXmlResponse($xml_response);

        }
        
        
        /**
         * Return details of a product searched by ASIN
         * 
         * @param int $asin_code ASIN code of the product to search
         * @return mixed simpleXML object
         */
        public function getItemByAsin($asin_code, $country)
        {
            $parameters = array("Operation"     => "ItemLookup",
                                "ItemId"        => $asin_code,
                                "ResponseGroup" => "ItemAttributes,Offers,Images,EditorialReview,Reviews");
                                
            $xml_response = $this->queryAmazon($parameters, $country);
            
            return $this->verifyXmlResponse($xml_response);
        }
        
        
        /**
         * Return details of a product searched by keyword
         * 
         * @param string $keyword keyword to search
         * @param string $product_type type of the product
         * @return mixed simpleXML object
         */
        public function getItemByKeyword($keyword, $product_type)
        {
            $parameters = array("Operation"   => "ItemSearch",
                                "Keywords"    => $keyword,
                                "SearchIndex" => $product_type);
                                
            $xml_response = $this->queryAmazon($parameters);
            
            return $this->verifyXmlResponse($xml_response);
        }

 

        public function CreateCart($parameters,$country="com")
        {
           
                                
            $xml_response = $this->queryAmazon($parameters,$country);
            
            return $this->verifyXmlResponse($xml_response);

        }

    }

?>