<?php

/***************** DO NOT EDIT THIS FILE *************************
******************************************************************

INFORMATION:
------------

This is a core theme file, you should not need to edit 
this file directly. Code changes maybe lost during updates.

LAST UPDATED: June 26th 2011
EDITED BY: MARK FAIL
------------------------------------------------------------------

******************************************************************/

$path=dirname(realpath($_SERVER['SCRIPT_FILENAME']));
$path_parts = pathinfo($path);
$p = str_replace("wp-content","",$path_parts['dirname']);	
$p = str_replace("themes","",$p);
$p = str_replace("PPT","",$p);

$p = str_replace("directorypress","",$p);
$p = str_replace("auctionpress","",$p);
$p = str_replace("couponpresspress","",$p);
$p = str_replace("shopperpress","",$p);
$p = str_replace("realtorpress","",$p);
$p = str_replace("couponpress","",$p);

$p = str_replace("template_","",$p);
$p = str_replace("\\\\","",$p);
$p = str_replace("////","",$p);
 
require( $p.'/wp-config.php' );

 
switch($_GET['action']){


	case "UserActionForm": {
	
		if($_GET['act'] == "login"){
		
			$creds = array();
			$creds['user_login']	 	= $_GET['data'];
			$creds['user_password'] 	= $_GET['data1'];
			if(strlen($_GET['cap']) > 0){
				$creds['captcha_code'] 		= $_GET['cap'];
				$_POST['captcha_code']		= $_GET['cap'];
				$_POST['si_code_log']		= $_GET['cap1'];
			}
			$creds['remember'] = true;
			 
			
			$user = wp_signon( $creds, false );
			if ( is_wp_error($user) ){
			
				echo $user->get_error_message();	
				print "<br/><br/><a href='' onClick=\"jQuery('#loginform').show();\">click here to try again</a>";
			
			}else{
			
				print "Welcome back ".$user->display_name."<br/><br/>";
				
				print "<p class='CheckoutBtn'><a href='javascript:void(0);' onClick=\"jQuery('#step1box').hide();jQuery('#step2box').show();;\" style='color:white;'>continue</a></p>";
				 
 			
			}
				
		
		}elseif($_GET['act'] == "register"){
		
		 
		
		}
 
 	
	
	} break;
 

 	case "icodes": {
 
	$dd = str_replace("http://","",str_replace("www.","",$_GET['mer']));
	$dd1 = explode("/",$dd);
	 

	// CHECK THIS PRODUCT DOESNT ALREADY EXIST		
	$result = mysql_query("SELECT $wpdb->posts.ID AS total FROM $wpdb->posts
	INNER JOIN $wpdb->postmeta ON
	($wpdb->posts.ID = $wpdb->postmeta.post_id AND $wpdb->postmeta.meta_key ='link' AND $wpdb->postmeta.meta_value='".PPTCLEAN($_GET['code'])."') 
	LIMIT 1", $wpdb->dbh) or die(mysql_error().' on line: '.__LINE__);
						
	$array = mysql_fetch_assoc($result);
					 
	if (empty($array['total'])) {
	
	// CREATE THE CUSTOM TITLE AND DESCRIPTION
	$ctitle = stripslashes(get_option("icodes_custom_title"));
	if($ctitle == ""){
		$CUSTOMTITLE = $_GET['title'];
	}else{	    
		$CUSTOMTITLE = str_replace("[title]",$_GET['title'],str_replace("[code]",$_GET['code'],str_replace("[merchant]",$_GET['merchant'],str_replace("[url]",$dd1[0],str_replace("[starts]",date('l jS \of F Y h:i:s A',strtotime($_GET['starts'])),str_replace("[ends]",date('l jS \of F Y h:i:s A',strtotime($_GET['exp'])),$ctitle))))));
	}
	$cdesc = stripslashes(get_option("icodes_custom_desc"));
	if($cdesc == ""){
		$CUSTOMDESC = $_GET['desc'];
	}else{
		$CUSTOMDESC = str_replace("[description]",$_GET['title'],str_replace("[code]",$_GET['code'],str_replace("[merchant]",$_GET['merchant'],str_replace("[url]",$dd1[0],str_replace("[starts]",date('l jS \of F Y h:i:s A',strtotime($_GET['starts'])),str_replace("[ends]",date('l jS \of F Y h:i:s A',strtotime($_GET['exp'])),$cdesc))))));
		  
	}
	
 	  $my_post = array();
	  $my_post['post_title'] 	= $CUSTOMTITLE;//$_GET['title']." at ".$dd1[0];
	  $my_post['post_content'] 	= $CUSTOMDESC;
	  $my_post['post_excerpt'] 	= $CUSTOMDESC;
	  $my_post['post_author'] 	= 1;
	  $my_post['post_status'] 	= get_option("icodes_import_status");
	  $my_post['post_category'] = array($_GET['catid']);
	  $my_post['tags_input'] = $dd1[0];
	  $POSTID = wp_insert_post( $my_post );	  
 
	  // EXTRA FIELDS
	  add_post_meta($POSTID, "code", $_GET['code']);
	  add_post_meta($POSTID, "starts", $_GET['starts']);
	  add_post_meta($POSTID, "expires", $_GET['exp']);
	  add_post_meta($POSTID, "url", $dd1[0]);	  
	  add_post_meta($POSTID, "hits", "1");
	  add_post_meta($POSTID, "link", str_replace("**","&",$_GET['url']));
	  add_post_meta($POSTID, "type", $_GET['type']);  
	  add_post_meta($POSTID, "image", $_GET['img']);

	  print '<div class="msg msg-ok"><p>Coupon Added Successfully</p></div>';

	}else{
		print '<div class="msg msg-error"><p>Coupon Already Exists</p></div>';
	}
 

	} break;

case "editSlider": {

$nowSlide = get_option("slider_array");

print '<input type="hidden" id="ppsedit" name="eid" value="'.$_GET['eid'].'">
 <table width="100%" border="0">
  <tr>
  
    <td valign="top"><b>Slider Title</b> <br /> <input type="text" name="s1" id="pps1"  style="width: 200px;  font-size:14px;" class="txt" value="'.$nowSlide[$_GET['eid']]['s1'].'" /> </td>
    <td><b>Title Description</b> <small>(max. 10 words)</small> <br /> <textarea name="s3" id="pps3" style="width: 200px;  font-size:14px; height:70px;" class="txt">'.$nowSlide[$_GET['eid']]['s3'].'</textarea> </td>
    <td><b>Main Description</b> <small>(max. 250 words)</small> <br /> <textarea name="s4" id="pps4" style="width: 200px;  font-size:14px; height:70px;" class="txt">'.$nowSlide[$_GET['eid']]['s4'].'</textarea></td>
  </tr>
  
  <tr>
    <td><b>Slider Image</b> <small>(650x X 265px)</small> <br/> <input type="text" name="s2" id="pps2"  style="width: 200px;  font-size:14px;" class="txt" value="'.$nowSlide[$_GET['eid']]['s2'].'" />
     <p><a href=\'javascript:void(0);\' onClick="toggleLayer(\'DisplayImages\'); add_image_next(0,\''.get_option("imagestorage_path").'\',\''.get_option("imagestorage_link").'\',\'pps2\');"> View Uploaded Images</a></p>	
    </td>
    <td valign="top"><b>Slider Clickable Link</b> <br /> <input type="text" name="s5" id="pps5"  style="width: 200px;  font-size:14px;" class="txt" value="'.$nowSlide[$_GET['eid']]['s5'].'" /> </td>
    <td valign="top"><b>Display Order</b><br /><select id="pps6" name="order" style="width: 100px;  font-size:14px;">';
	
	 $i=1; while($i<20){ if($i == $nowSlide[$_GET['eid']]['order']){ $sel ="selected=selected"; }else{ $sel =""; } echo '<option '.$sel.'>'.$i.'</option>'; $i++; } 
	 
	 print '</select></td>
  </tr> 
  
<td colspan="3"><p><a href="#" class="premiumpress_button" style="color:white;" Onclick="UpdateSliderItem();" />Update Slider</a></td>
</tr>
</table>';


} break;

case "deleteSlider": {

$nowSlide = get_option("slider_array");
$newSlide = array();
$c=0; foreach($nowSlide as $slide){ 


	if($c != $_GET['eid']){
	
			$newSlide[$c]['order'] = $slide['order'];
			$newSlide[$c]['s1'] = $slide['s1'];
			$newSlide[$c]['s2'] = $slide['s2'];
			$newSlide[$c]['s3'] = $slide['s3'];
			$newSlide[$c]['s4'] = $slide['s4'];
			$newSlide[$c]['s5'] = $slide['s5'];
			
	}else{
	print "<div style='padding:5px; background:green;color:white; margin-right:20px; margin-bottom:20px;'>Deleted Slider Successfully - <a href='admin.php?page=display' style='color:white; font-weight:bold;'>Click here to show the update slider table.</a></div>";
	}
	$c++;
}

	update_option("slider_array",$newSlide);
	
	//print "Slider Deleted";
	
} break;

case "updateSlider": {

	$nowSlide = get_option("slider_array");
	if(is_array($nowSlide)){ $c= count($nowSlide);; }else{ $c=0; }
	
	
	if($_GET['eid'] == "0"){
	
		$nowSlide[$c]['order'] = $_GET['s6'];
		$nowSlide[$c]['s1'] = $_GET['s1'];
		$nowSlide[$c]['s2'] = $_GET['s2'];
		$nowSlide[$c]['s3'] = $_GET['s3'];
		$nowSlide[$c]['s4'] = $_GET['s4'];
		$nowSlide[$c]['s5'] = $_GET['s5']; 
	
	}else{
	
		$nowSlide[$_GET['eid']]['order'] = $_GET['s6'];
		$nowSlide[$_GET['eid']]['s1'] = $_GET['s1'];
		$nowSlide[$_GET['eid']]['s2'] = $_GET['s2'];
		$nowSlide[$_GET['eid']]['s3'] = $_GET['s3'];
		$nowSlide[$_GET['eid']]['s4'] = $_GET['s4'];
		$nowSlide[$_GET['eid']]['s5'] = $_GET['s5']; 
	}	
	
	update_option("slider_array",$nowSlide);
	
	print "<div style='padding:5px; background:green;color:white; margin-right:20px; margin-bottom:20px;'>Slider Updated Successfully  - <a href='admin.php?page=display' style='color:white; font-weight:bold;'>Click here to show the update slider table.</a></div>";


} break;

case "cattext": {

	$text = get_option("cat_extra_text_".$_GET['current']);
	print "Category Description <br ><small>Enter a description or text for this category. Allows HTML code.</small>
	<textarea name=\"adminArray[cat_extra_text_".$_GET['current']."]\" rows=\"11\" cols=\"83\">".$PPT->CategoryExtras($_GET['current'],"text")."</textarea><br><br>
	Category Image<br><small> <b>(only used with some templates, accepts http:// image links and selection) </small><br>";
	
	print '<input name="adminArray[cat_extra_image_'.$_GET['current'].']" type="text" id="catlogo" style="width: 550px;  font-size:14px;" class="txt" value="'.get_option("cat_extra_image_".$_GET['current']).'" /><br />';
	
	print '<input onClick="toggleLayer(\'DisplayImages\'); add_image_next(0,\''.get_option("imagestorage_path").'\',\''.get_option("imagestorage_link").'\',\'catlogo\');" type="button"   value="View Images"  />';

 	print '<input  type="button" size="36" name="upload_catlogo" value="Upload Image" onClick="ChangeCatLogo();"  />';
	
 


} break;

case "catprice": {

	$price = get_option("CatPrice_".$_GET['current']);
   if($price == ""){ $price=0; }
	print '<b>Current Price</b> <br />'.get_option("currency_code").'<input type="text" name="adminArray[CatPrice_'.$_GET['current'].']" value="'.$price.'" >';
	
	print '<input class="premiumpress_button" type="submit" value="Update Price" style="color:white;background:red;" />';


} break;


	case "changestate": {
 	
	include($p."/wp-content/themes/".GetThemeName()."/PPT/func/func_states.php");
	if(isset($GLOBALS['_LANG']['_404_title'])){ $tt = SPEC($GLOBALS['_LANG']['_404_title']); }else{  $tt = "State or Province"; }
	
	if(in_array($_GET['current'],$state_included)){
	
			
			if($_GET['current'] == "United States"){$states = $state_usa;}
			if($_GET['current'] == "China"){$states = $state_china;}
			if($_GET['current'] == "France"){$states = $state_france;}
			if($_GET['current'] == "Germany"){$states = $state_germany;}
			if($_GET['current'] == "United Kingdom"){$states = $state_uk;}
			if($_GET['current'] == "Spain"){$states = $state_spain;}
			if($_GET['current'] == "Scotland"){$states = $state_scotland;}
			if($_GET['current'] == "Romania"){$states = $state_romania;}
			if($_GET['current'] == "Canada"){$states = $state_canada;}
			if($_GET['current'] == "India"){$states = $state_india;}
			if($_GET['current'] == "Indonesia"){$states = $state_indonesia;}
			if($_GET['current'] == "Australia"){$states = $state_australia;}
			if($_GET['current'] == "Malaysia"){$states = $state_malaysia;}
			
			 

			if(isset($_GET['ship'])){
			$string = '<p class="f_half left"><label>'.$tt.'</label><br /><select name="shipping[state]" class="short" id="state"><option value="0">-------------</option>';
			}else{
			$string = '<p class="f_half left"><label>'.$tt.'</label><br /><select name="form[state]"  class="short" id="state"><option value="0">-------------</option>';
			}
			
			if(isset($_GET['cstate'])){
			$string .= '<option value="'.$_GET['cstate'].'" selected=selected>'.$_GET['cstate'].'</option>';
			}			 
			
			foreach($states as $val){
			
				if(isset($_GET['val']) && $_GET['val'] == 100){
				
				$tv = get_option('citytax_'.$val);
				$string .= '<option value="'.$val.'">'.$val.'';
				if(strlen($tv) > 0){
					$string .= ' (Currently: '.get_option('citytax_'.$val).'%)';
				}
				$string .= '</option>';
				}else{
				$string .= '<option value="'.$val.'">'.$val.'</option>';
				}
				
			}
			
			$string .= '</select></p>';
			print $string;
	
	}else{
	 
		if(isset($_GET['ship'])){
		print  '<p class="f_half left"><label class="col1">'.$tt.'</labe<br /><input type="text" name="shipping[state]" class="short" size="35" maxlength="200" id="state"/></p>';
		}else{
		print  '<p class="f_half left"><label class="col1">'.$tt.'</labe<br /><input type="text" name="form[state]" class="short" size="35" maxlength="200" id="state"/></p>';
		}
	
		 
	}
	
		
	
	} break;






case "add_image_next": {
 
	// GET IMAGE DATA FROM THE FOLDER
	$d = dir($_GET['path']);
	while (false !== ($entry = $d->read())) {
		if (preg_match("/(\.gif$)/i", strtolower($entry)) || preg_match("/(\.jpg$)/i", strtolower($entry)) || preg_match("/(\.jpeg$)/i", strtolower($entry)) || preg_match("/(\.png$)/i", strtolower($entry))){
		
		if(isset($_GET['search']) && strlen($_GET['search']) > 1 && $_GET['search'] != "undefined" ){
	 
			$pos = strpos($entry, $_GET['search']); 
			if ($pos === false) {}else{$pics[] = $entry;}
			
			}else{
				$pics[] = $entry;
			}
		}
	}
	 
	$d->close();
	$checkbox=1;
	$numPerRow = 25;
	$numPics = count($pics);
	if(!isset($_GET['p'])){ $c_page = 0; }else { $c_page = $_GET['p']*$numPerRow; } 
	$dd = ceil($numPics/$numPerRow);

	print '<div style="padding:10px;border:1px solid #ddd; background:#efefef; width:98%">';
	
	?>
	<input name="search" type="text" style="font-size:18px; width:200px; background:#ceffcf; border:2px solid #5ae15d;" id="searchBox2" value="keyword..">
	<input  type="button" style="font-size:18px; background:#a70303; color:white;padding:5px;" value="Search" onClick="document.getElementById('searchBox1').value = document.getElementById('searchBox2').value; add_image_next(0,'<?php echo $_GET['path']; ?>','<?php echo $_GET['link']; ?>','<?php echo $_GET['type']; ?>','<?php echo $_GET['div']; ?>');">
	<div style="clear:both;"></div>
    
	<?php


	for ($i=0; $i < $numPics; $i++){ 
	if($i > $c_page-1 && $i < $c_page+$numPerRow ){
	$currThumb = $thispic + $i; if(strlen($pics[$currThumb]) > 1){ ?>

	<div style="float:left; width:140px; margin:10px; margin-left:0px; border:1px solid #dddddd; background:#fff; padding:5px;">
	<div style="height:110px; overflow:hidden;">
	<a href="http://<?php echo $_GET['link'].$pics[$currThumb] ?>" target="_blank" rel="image_group"><img src="http://<?php echo $_GET['link'].$pics[$currThumb]; ?>" style="max-width:140px;" border="0" /></a>
	</div>
	<div style="background:#efefef; border:1px solid #ddd; padding:5px; margin-top:10px;">  
	<!--<a href="http://<?php echo $_GET['link'].$pics[$currThumb] ?>" target="_blank" rel="image_group"><img src="<?php echo $GLOBALS['template_url']; ?>/images/premiumpress/led-ico/find.png" align="middle"> View</a> - -->
	<a href="#" onclick="document.getElementById('<?php echo $_GET['type']; ?>').value=document.getElementById('<?php echo $_GET['type']; ?>').value + ',<?php echo $pics[$currThumb]; ?>'; toggleLayer('DisplayImages');"><img src="<?php echo $GLOBALS['template_url']; ?>/images/premiumpress/led-ico/accept.png" align="middle"> Select </a>
	 </div>
	<small><b><?php echo $pics[$currThumb] ?></b></small>
	</div>

	<?php $checkbox++; } } } ?>
	<div class="clearfix"></div>
	
	<div class="pagination">
	<ul>
	<li><b>Showing Page <?php echo $_GET['p']+1; ?> of <?php if($dd ==0){ echo "1"; }else{ echo $dd; }; ?></b></li>
	<?php $pc = $dd;while($pc > 0){$pnum = $pc; ?>
	<li><a href='javascript:void(0);' onClick="add_image_next(<?php echo $pnum-1; ?>,'<?php echo $_GET['path']; ?>','<?php echo $_GET['link']; ?>','<?php echo $_GET['type']; ?>','<?php echo $_GET['div']; ?>');"><?php echo $pc; ?></a></li>
	<?php $pc--; } ?>
	</ul>
	</div>

<?php } break;













case "add_video_next": {

	// GET IMAGE DATA FROM THE FOLDER
	$d = dir($_GET['path']);
 
	while (false !== ($entry = $d->read())) {
	
		//if (preg_match("/(\.gif$)/i", strtolower($entry)) || preg_match("/(\.jpg$)/i", strtolower($entry)) || preg_match("/(\.jpeg$)/i", strtolower($entry)) || preg_match("/(\.png$)/i", strtolower($entry))){
		
		if(isset($_GET['search']) && strlen($_GET['search']) > 1 && $_GET['search'] != "undefined" ){
	 
			$pos = strpos($entry, $_GET['search']); 
			if ($pos === false) {}else{$pics[] = $entry;}
			
			}else{
				$pics[] = $entry;
			}
		//}
	}
	
	$d->close();
	$checkbox=1;
	$numPerRow = 25;
	$numPics = count($pics);
	if(!isset($_GET['p'])){ $c_page = 0; }else { $c_page = $_GET['p']*$numPerRow; } 
	$dd = ceil($numPics/$numPerRow);

	print '<div style="padding:10px;border:1px solid #ddd; background:#efefef; width:98%">';
	
	?>
	<input name="search" type="text" style="font-size:18px; width:200px; background:#ceffcf; border:2px solid #5ae15d;" id="searchBox2" value="keyword..">
	<input  type="button" style="font-size:18px; background:#a70303; color:white;padding:5px;" value="Search" onClick="document.getElementById('searchBox1').value = document.getElementById('searchBox2').value; add_image_next(0,'<?php echo $_GET['path']; ?>','<?php echo $_GET['link']; ?>','<?php echo $_GET['type']; ?>','<?php echo $_GET['div']; ?>');">
	<div style="clear:both;"></div>
    
	<?php

	for ($i=0; $i < $numPics; $i++){  
	if($i > $c_page-1 && $i < $c_page+$numPerRow ){
	
	$currThumb = $thispic + $i; if(strlen($pics[$currThumb]) > 3){ ?>

	<div style="float:left; width:140px; margin:10px; margin-left:0px; border:1px solid #dddddd; background:#fff; padding:5px;">
	<div style="height:110px; overflow:hidden;">
	<a href="http://<?php echo $_GET['link'].$pics[$currThumb] ?>" target="_blank" rel="image_group"><img src="http://<?php echo $_GET['link'].$pics[$currThumb]; ?>" style="max-width:140px;" border="0" /></a>
	</div>
	<div style="background:#efefef; border:1px solid #ddd; padding:5px; margin-top:10px;">  
	<!--<a href="http://<?php echo $_GET['link'].$pics[$currThumb] ?>" target="_blank" rel="image_group"><img src="<?php echo $GLOBALS['template_url']; ?>/images/premiumpress/led-ico/find.png" align="middle"> View</a> - -->
	<a href="#" onclick="document.getElementById('<?php echo $_GET['type']; ?>').value=document.getElementById('<?php echo $_GET['type']; ?>').value + ',<?php echo $pics[$currThumb]; ?>'; toggleLayer('DisplayImages');"><img src="<?php echo $GLOBALS['template_url']; ?>/images/premiumpress/led-ico/accept.png" align="middle"> Select </a>
	 </div>
	<small><b><?php echo $pics[$currThumb] ?></b></small>
	</div>

	<?php $checkbox++; } } } ?>
	<div class="clearfix"></div>
	
	<div class="pagination">
	<ul>
	<li><b>Showing Page <?php echo $_GET['p']+1; ?> of <?php if($dd ==0){ echo "1"; }else{ echo $dd; }; ?></b></li>
	<?php $pc = $dd;while($pc > 0){$pnum = $pc; ?>
	<li><a href='javascript:void(0);' onClick="add_image_next(<?php echo $pnum-1; ?>,'<?php echo $_GET['path']; ?>','<?php echo $_GET['link']; ?>','<?php echo $_GET['type']; ?>','<?php echo $_GET['div']; ?>');"><?php echo $pc; ?></a></li>
	<?php $pc--; } ?>
	</ul>
	</div>

<?php } break;














case "icodesList":{

	switch($_GET['type']){
	
		case "Category":{	
		
			$list = get_option('icodes_categorylist');
			print '<select name="icodes_s_3">';
			foreach($list as $cat){
			print '<option value="'.$cat['id'].'">'.str_replace("_"," ",$cat['name']).'</option>';	
			}
			print '</select>';
			
		} break;
		case "Network":{ 	
		
			$list = get_option('icodes_networklist');
			print '<select name="icodes_s_3">';
			foreach($list as $cat){
			print '<option value="'.$cat['id'].'">'.str_replace("_"," ",$cat['name']).'</option>';	
			}
			print '</select>';	
		
		} break;
		case "Merchant":{ 	
		
			$list = get_option('icodes_merchantlist');			
			
			print '<select name="icodes_s_3">';
			foreach($list as $cat){
			print '<option value="'.$cat['id'].'">'.str_replace("_"," ",$cat['name_merchant']).'</option>';	
			}
			print '</select>';
			
		} break;
	
	}
 

} break;
















case "changeProperty": {

if(is_numeric($_GET['d'])){

	$GLOBALS['premiumpress']['language'] = get_option("language");
	$PPT->Language();

	$GLOBALS['premiumpress']['thumbresize'] 		= get_option("thumbresize");

	$post = get_post($_GET['d']); 
	
	$PASSCODE = '<h1>%title%</h1>
			 
			 <img src="%img%" width="80" height="70" alt="%title%" />
			 
			 <p class="title">%price%</p>
			  
			 <p class="desc">%excerpt%..</p>         
			 
			 <div class="clearfix"></div>
			 
			 <div style="border-top:1px dotted #ccc;font-size:16px; padding-top:20px;"> 
			 
			 
			<ul class="item_stats" style="margin:0;">
					 
					<li class="beds">%beds% '.SPEC($GLOBALS['_LANG']['_bedrooms']).'</li>
					<li class="baths">%baths% '.SPEC($GLOBALS['_LANG']['_bathrooms']).'</li>
				</ul>        
		  
			 <div class="clearfix"></div>
			 
			  <br /><p><a href="%link%" class="btn">'.SPEC($GLOBALS['_LANG']['_homepage6']).'</a></p>';
			 
			 $DisplayCode = str_replace("%title%",$post->post_title,str_replace("%img%",$PPT->Image($post->ID,"m"),str_replace("%price%",$PPT->Price(get_post_meta($post->ID, "price", true),get_option('currency_code'),"l",1),str_replace("%excerpt%",substr($post->post_excerpt,0,255),str_replace("%beds%",get_post_meta($post->ID, "bedrooms", true),str_replace("%baths%",get_post_meta($post->ID, "bathrooms", true),str_replace("%link%",get_permalink($post->ID),$PASSCODE)))))));
			 
	
	print  $DisplayCode;

}else{
 
print  '<img src="'.$PPT->ImageCheck(trim($_GET['d']),"full").'" style="max-width:600px;max-height:450px;">';

}


} break;



























	case "addAmazonProduct": { 
 
	 $SQL = "SELECT count($wpdb->postmeta.meta_key) AS total
	 FROM $wpdb->postmeta
	 WHERE $wpdb->postmeta.meta_key='amazon_guid' AND $wpdb->postmeta.meta_value = '".$_GET['asnid']."'
	 LIMIT 1";	
			 
	 $result = mysql_query($SQL);			 
	 $array = mysql_fetch_assoc($result);
	
	 if($array['total'] > 0){
	 
	 print '<div class="msg msg-error"><p>You have already imported this product before.</p></div>';
	 die();
	 
	 }
 		
	$obj = new AmazonProductAPI();
	$result = $obj->getItemByAsin($_GET['asnid'],$_GET['country']);			
		 
    foreach($result->Items->Item as $val){
	
	//die(print_r($val));
 
   
	$data['title'] 		= str_replace("!!aaqq","",$val->ItemAttributes->Title);
	$data['asin'] 		= str_replace("!!aaqq","",$val->ASIN);
	$data['url'] 		= str_replace("!!aaqq","",$val->DetailPageURL);
	//$data['qty']		= str_replace("!!aaqq","",$val->ItemAttributes->NumberOfItems);
	$data['desc']		= nl2br(str_replace(".",",<br/>",$val->EditorialReviews->EditorialReview->Content));
	$data['image'] 		= str_replace("!!aaqq","",$val->LargeImage->URL);
	$data['thumbnail']	= str_replace("!!aaqq","",$val->MediumImage->URL);
	$data['images'] 	= "";
	$data['warranty']	= str_replace("!!aaqq","",$val->ItemAttributes->Warranty);	
	$data['price'] 		= str_replace("!!aaqq","",$val->ItemAttributes->ListPrice->Amount);

	if( $data['price'] == "Too low to display"){
		
	print '<div class="msg msg-error"><p>Product price is invalid as its a promotional item Amazon is running and cannot be added.</p></div>';
	die();
		
	}
	
	if($data['price'] == ""){
		$data['price'] = str_replace("!!aaqq","",$val->OfferSummary->LowestNewPrice->Amount);
	}
	//die(print_r($val).$data['price']);
	//die(print_r($val));
	
	if(isset($val->Offers->Offer->OfferListing->Price->Amount) && strlen($val->Offers->Offer->OfferListing->Price->Amount) > 1){
	
			$data['old_price'] = $data['price'];
			$data['price'] 	=  str_replace("!!aaqq","",$val->Offers->Offer->OfferListing->Price->Amount);	
	}	
 
	// Load price options
	if($_GET['country'] == "jp"){
	
	}else{
		$data['old_price'] = substr($data['old_price'],0, -2).".".substr($data['old_price'],-2);
 		$data['price'] = substr($data['price'],0, -2).".".substr($data['price'],-2);
	}	
	
	
	

 

	$AFFLINK = "http://www.amazon.".$_GET['country']."/o/ASIN/%asin%/%amazon_id%";
	$AFFLINK = str_replace("%asin%",$data['asin'],$AFFLINK);
	$AFFLINK = str_replace("%amazon_id%",'YOURUSERID',$AFFLINK);	
	
	// IMAGE SETS	
	if(isset($val->ImageSets->ImageSet)){	
	$i=1;
		foreach($val->ImageSets->ImageSet as $img){ if($i < 6){
			$data['images'] .= $img->LargeImage->URL.",";
		$i++; } }
	}
 
	
	// GET PRODUCT FEATURES
	$excerpt="<ul>";
	foreach($val->ItemAttributes->Feature as $feature){
	$excerpt .="<li>".$feature."</li>";
	}
	$excerpt.="</ul>";	

	//	GET ATTRIBUTES
	$extra_data = "<ul class=ExtraData>";
	foreach($val->ItemAttributes as $at1){foreach($at1 as $key => $att){
	$extra_data .= "<li><span>".$key."</span>:";
		if(is_array($att)){
			foreach($att as $in){
				$extra_data .= $in;
			}
		}else{
			$extra_data .= $att;
		}
	$extra_data .= "</li>";
	}}

	$extra_data .="</ul>";
 	
	
	if(strlen($excerpt) < 10){ $excerpt = $extra_data; }		
	
		$data['desc'] 		= str_replace(":"," : ",$data['desc']);
		$excerpt 		= str_replace(":"," : ",$excerpt);
		//die($_GET['catid']."<--");
		
		if(strlen($data['title']) > 45){
		$ssss = explode(" ",str_replace("with","",$data['title']));
		$name = ""; $i=0;
			 while($i < count($ssss)){
				 if(strlen($name) < 45){
					$name .= $ssss[$i]." ";
					}
			  $i++;		 
			 }		 
		}else{
		$name  = $data['title'];
		}
	 
 	  $my_post = array();
	  $my_post['post_title'] 	= $name;
	  $my_post['post_content'] 	= $data['desc'].$extra_data;
	  $my_post['post_excerpt'] 	= strip_tags(substr($data['desc'],0,230))."...";
	  $my_post['post_author'] 	= 1;
	  $my_post['post_status'] 	= "publish";
	  $my_post['post_category'] = explode(",",$_GET['catid']);
	  $my_post['tags_input'] = str_replace(" ",",",str_replace("-","",$data['title']));;
	  $POSTID = wp_insert_post( $my_post );	  
	  
	  $data['price'] 		= str_replace(",","",$data['price']);
	  $data['old_price']  	= str_replace(",","",$data['old_price']);
	  
	  // EXTRA FIELDS
	  add_post_meta($POSTID, "amazon_link", $AFFLINK);
	  add_post_meta($POSTID, "amazon_guid", $data['asin']);
	  add_post_meta($POSTID, "price", $data['price']);
	  if(isset($data['old_price']) && strlen($data['old_price']) > 1){ add_post_meta($POSTID, "old_price", $data['old_price']); }
	  add_post_meta($POSTID, "warranty", $data['warranty']);
	  
	  add_post_meta($POSTID, "image", $data['image']);
	  add_post_meta($POSTID, "images", $data['images']);	  
	  add_post_meta($POSTID, "qty", 1);	  
	  add_post_meta($POSTID, "featured", "no");
	  
	  // CHECK FOR COMMENTS	  
	 /* $time = current_time('mysql', $gmt = 0);	
	    
	  if(isset($val->CustomerReviews->Review)){ foreach($val->CustomerReviews->Review as $review){

		$data = array(
			'comment_post_ID' => $POSTID,
			'comment_author' => $review->Reviewer->Name,
			'comment_author_email' => 'admin@admin.com',
			'comment_author_url' => 'http://',
			'comment_content' => nl2br($review->Content),
			//'comment_type' => ,
			'comment_parent' => 0,
			'user_ID' => 1,
			'comment_author_IP' => '127.0.0.1',
			'comment_agent' => 'Mozilla/5.0 (Windows; U; Windows NT 5.1; en-US; rv:1.9.0.10) Gecko/2009042316 Firefox/3.0.10 (.NET CLR 3.5.30729)',
			'comment_date' => $review->Date,
			'comment_date_gmt' => $time,
			'comment_approved' => 1,
		);
		
		wp_insert_comment($data);
		
	  } }*/
 
 
	print '<div class="msg msg-ok"><p>Product Added Successfully</p></div>';
	
	}
			
			
	
	} break;





	case "addEbayProduct": {


	 $SQL = "SELECT count($wpdb->postmeta.meta_key) AS total
	 FROM $wpdb->postmeta
	 WHERE $wpdb->postmeta.meta_key='ebay_ID' AND $wpdb->postmeta.meta_value = '".$_GET['ID']."'
	 LIMIT 1";	
			 
	 $result = mysql_query($SQL);			 
	 $array = mysql_fetch_assoc($result);
	
	 if($array['total'] > 0){
	 
	 print '<div class="msg msg-error"><p>You have already imported this product before.</p></div>';
	 die();
	 
	 }	
	 
	$appid 		= $_GET['API'];  // Replace with your own AppID

	// API request variables
	$endpoint 	= 'http://svcs.ebay.com/services/search/FindingService/v1';  // URL to call
	$version 	= '1.0.0';  // API version supported by your application
	$globalid 	= $_GET['country'];  // Global ID of the eBay site you want to search (e.g., EBAY-DE)
	$query 		= $_GET['ID'];  // You will need to supply your own query
	$SafeQuery 	= urlencode($query);  // Make the query URL-friendly
	
	// Construct the findItemsByKeywords call 
	$apicall = "$endpoint?";
	$apicall .= "OPERATION-NAME=findItemsByKeywords";
	$apicall .= "&SERVICE-VERSION=$version";
	$apicall .= "&SECURITY-APPNAME=$appid";
	$apicall .= "&GLOBAL-ID=$globalid";
	$apicall .= "&keywords=$SafeQuery";
	$apicall .= "&paginationInput.entriesPerPage=2"; // items per page
	$apicall .= "&paginationInput.pageNumber=1&outputSelector(0)=SellerInfo&outputSelector(1)=StoreInfo"; // page nav
	$apicall .= "&sortOrder=CurrentPriceHighest";
	if(strlen($_GET['aff1']) > 1){
	$apicall .= "&affiliate.networkId=9";
	$apicall .= "&affiliate.trackingId=".$_GET['aff1'];
	$apicall .= "&affiliate.customId=".$_GET['aff2'];
	} 
	 
	//print $apicall;
	$resp = simplexml_load_file($apicall);
	//print_r($resp);
	if($resp->paginationOutput->totalEntries =='0'){
	
	
	 print '<div class="msg msg-error"><p>Item Not Added. eBay have restricted this item.</p></div>';
	 die();
	 
	
	}

	if(strlen($resp->errorMessage->error->message) > 2){
	
	print $resp->errorMessage->error->message;
	
	}else{
	// Check to see if the response was loaded, else print an error
	 if ($resp) {
	 
		 foreach($resp->searchResult->item as $item) {	 


			  $my_post = array();
			  $my_post['post_title'] 	= str_replace("!!aaqq","",$item->title);
			  $my_post['post_content'] 	= str_replace("!!aaqq","",$item->subtitle);
			  $my_post['post_excerpt'] 	= str_replace("!!aaqq","",$item->subtitle);
			  $my_post['post_author'] 	= 1;
			  $my_post['post_status'] 	= "publish";
			  $my_post['post_category'] = array($_GET['catid']);
			  
			  $POSTID = wp_insert_post( $my_post );	  
			  
			  
			  // EXTRA FIELDS
			  add_post_meta($POSTID, "buy_link", str_replace("!!aaqq","",$item->viewItemURL));
			  add_post_meta($POSTID, "ebay_ID", str_replace("!!aaqq","",$_GET['ID']));
			  add_post_meta($POSTID, "price", str_replace("!!aaqq","",$item->sellingStatus->currentPrice));		  
			  add_post_meta($POSTID, "image", str_replace("!!aaqq","",$item->galleryURL)); 	  
			  add_post_meta($POSTID, "qty", 1);	
			  add_post_meta($POSTID, "redirect", "yes");
			  add_post_meta($POSTID, "featured", "no");
			  
			  print '<div class="msg msg-ok"><p>Product Added Successfully</p></div>';
		 
		 }
	 
	 }else{
	 
	 print '<div class="msg msg-error"><p>Product Import Failed. '.$resp->errorMessage->error->message.'</p></div>';
	 }
	}

	
	
	
	} break;


case "addMovie" : {
 

	switch($_GET['network']){
	
	case "metacafe": { 
	 
	 
	include($p."/wp-content/themes/".GetThemeName()."/PPT/class/class_videoproviders.php");
	$embedCode = new VideoProvider();
	
	$data =  $embedCode->getEmbedCode("http://www.metacafe.com/watch/".$_GET['ID']."/00/"); 
 
	if(is_array($data)){
	$my_post = array();
	$my_post['post_title'] 		= $data['title'];
	$my_post['post_content'] 	= strip_tags($data['desc']);
	$my_post['post_excerpt'] 	= substr(strip_tags($data['desc']),0,200);
	$my_post['post_author'] 	= 1;
	$my_post['post_status'] 	= "publish";
	$my_post['post_category'] 	= explode(",",$_GET['catid']);
	$my_post['tags_input'] 		= str_replace(" ",",",str_replace("-","",$data['title']));
	$POSTID = wp_insert_post( $my_post );	
	 	
	// EXTRA FIELDS
	add_post_meta($POSTID, "MoveID", $_GET['ID']);	
	add_post_meta($POSTID, "image", "http://www.metacafe.com/thumb/".$_GET['ID'].".jpg");
	//add_post_meta($POSTID, "author", $sxml->channel->item->author);
	add_post_meta($POSTID, "code", $data['embed']);
	add_post_meta($POSTID, "embed", "1");
	
	print '<div class="msg msg-ok"><p>MetaCafe Video Added Successfully</p></div>';
	
	}else{
	print '<div class="msg msg-error"><p>MetaCafe Video Failed</p></div>';
	}
	
	} break;

	case "youtube": {
		
			include($p."/wp-content/themes/".GetThemeName()."/PPT/class/class_youtube.php");
			 
			
			$youtube 	= new YouTube( $_GET['ID'] );
			
			$meta	 	= $youtube->get_meta();
			$author		= $youtube->get_author();
			$comments	= $youtube->get_comments();
			
			 
				  $my_post = array();
				  $my_post['post_title'] 	= $meta['title'];
				  $my_post['post_content'] 	= nl2br( $meta['description'] );
				  $my_post['post_excerpt'] 	= substr($meta['description'],0,200);
				  $my_post['post_author'] 	= 1;
				  $my_post['post_status'] 	= "publish";
				  $my_post['post_category'] = explode(",",$_GET['catid']);
				  $my_post['tags_input'] = str_replace(" ",",",str_replace("-","",$data['title']));;
				  $POSTID = wp_insert_post( $my_post );	  
			 
			 
					// EXTRA FIELDS
					add_post_meta($POSTID, "MoveID", str_replace("11111111111111111","",$_GET['ID']));
					add_post_meta($POSTID, "image", str_replace("11111111111111111","",$meta['thumb']));
					add_post_meta($POSTID, "duration", sprintf( "%0.2f", str_replace("11111111111111111","",$meta['duration']) / 60 ));
					add_post_meta($POSTID, "rating", str_replace("11111111111111111","",$meta['rating']));
					add_post_meta($POSTID, "author", str_replace("11111111111111111","",$author['username']));
					add_post_meta($POSTID, "location", str_replace("11111111111111111","",$author['location']));
					add_post_meta($POSTID, "featured", "no");
					//add_post_meta($POSTID, "embed", str_replace("11111111111111111","",$meta['embed']));
					add_post_meta($POSTID, "hits", str_replace("11111111111111111","",$meta['views']));
				
					
				  if(is_array($comments['comments'])){ foreach( $comments['comments'] as $comment ) { 
			
					$data = array(
						'comment_post_ID' => $POSTID,
						'comment_author' => $review->Reviewer->Name,
						'comment_author_email' => 'admin@admin.com',
						'comment_author_url' => 'http://',
						'comment_content' => nl2br($comment),
						//'comment_type' => ,
						'comment_parent' => 0,
						'user_ID' => 1,
						'comment_author_IP' => '127.0.0.1',
						'comment_agent' => 'Mozilla/5.0 (Windows; U; Windows NT 5.1; en-US; rv:1.9.0.10) Gecko/2009042316 Firefox/3.0.10 (.NET CLR 3.5.30729)',
						'comment_date' => $review->Date,
						'comment_date_gmt' => $time,
						'comment_approved' => 1,
					);
					
					wp_insert_comment($data);
					
				  }  }
				  
				  print '<div class="msg msg-ok"><p>YouTube Video Added Successfully</p></div>';

		  
	} break;
	   
	}
		   

}




case "WishList":{  

	if($_GET['act'] == "add"){

		$RUN_QUERY = "SELECT count(".$wpdb->prefix."postmeta.meta_value) AS total FROM ".$wpdb->prefix."postmeta WHERE ".$wpdb->prefix."postmeta.meta_value='".$_GET['itemID']."' LIMIT 1"; 
		 
		
		$result1 = mysql_query($RUN_QUERY, $wpdb->dbh) or die(mysql_error().' on line: '.__LINE__);						
		$array = mysql_fetch_assoc($result1);
		 
		if($array['total'] == 0){
 
		$my_post = array();
		$my_post['post_title'] 		= $userdata->user_login." has added product ID ".$_GET['itemID']." to their wishlist.";
		$my_post['post_content'] 	= "";
		$my_post['post_excerpt'] 	= "";
		$my_post['post_status'] 	= "publish";
		$my_post['post_type'] 		= "ppt_wishlist";
		$my_post['post_author'] 	= $userdata->ID;
		$POSTID 					= wp_insert_post( $my_post );
		add_post_meta($POSTID, "itemID", $_GET['itemID']);	
		add_post_meta($POSTID, "userID", $userdata->ID);
		
		print "<div style='background:#009800;color:#fff;padding:5px;'>".getProductName($_GET['itemID'])." has been added to your wishlist. <a href='".get_option("wishlist_url")."' style='color:white;text-decoration:underline;'>Click Here to view your wishlist.</a> </div>";
		
		}else{
		
		print "<div style='background:#bc1b00; color:#fff;padding:5px;'>".getProductName($_GET['itemID'])." is already on your wishlist. <a href='".get_option("wishlist_url")."' style='color:white;text-decoration:underline;'>Click Here to view your wishlist.</a> </div>";
		
		}
		
	}elseif($_GET['act'] == "delete"){
	
	wp_delete_post($_GET['itemID']);
	
	print "item removed";
	
	}

} break;

case "JobWatchList":{  

	if($_GET['act'] == "add"){

		$RUN_QUERY = "SELECT count(".$wpdb->prefix."postmeta.meta_value) AS total FROM ".$wpdb->prefix."postmeta WHERE ".$wpdb->prefix."postmeta.meta_value= ('".$_GET['itemID']."-".$userdata->ID."') LIMIT 1"; 
		 
		
		$result1 = mysql_query($RUN_QUERY, $wpdb->dbh) or die(mysql_error().' on line: '.__LINE__);						
		$array = mysql_fetch_assoc($result1);
		 
		if($array['total'] == 0){
 
		$my_post = array();
		$my_post['post_title'] 		= "[".$userdata->user_login."] has added Job ID [".$_GET['itemID']."] to their watch list.";
		$my_post['post_content'] 	= "";
		$my_post['post_excerpt'] 	= "";
		$my_post['post_status'] 	= "publish";
		$my_post['post_type'] 		= "ppt_watchlist";
		$my_post['post_author'] 	= $userdata->ID;
		$POSTID 					= wp_insert_post( $my_post );
		
		add_post_meta($POSTID, "postID", $_GET['itemID']);
	 	add_post_meta($POSTID, "DuplicateKey", $_GET['itemID']."-".$userdata->ID);
		
		print "<div style='background:#009800;color:#fff;padding:5px;'>Your has been added to your wishlist.  </div>";
		
		}else{
		 
		print "<div style='background:#bc1b00; color:#fff;padding:5px;'>This job listing is already on your watchlist.</div>";
		
		}
		
	}elseif($_GET['act'] == "delete"){
	
	wp_delete_post($_GET['itemID']);
	
	print "item removed";
	
	}

} break;



}

?>