<?php

/***************** DO NOT EDIT THIS FILE *************************
******************************************************************

INFORMATION:
------------

This is a core theme file, you should not need to edit 
this file directly. Code changes maybe lost during updates.

LAST UPDATED: June 26th 2011
EDITED BY: MARK FAIL
------------------------------------------------------------------

******************************************************************/

class PremiumPressImport {

	function StartImport($system, $db_prefix=""){
	
		global $wpdb; $IMPORTCOUNTER=0;
 
		
		$db_one = mysql_connect(DB_HOST, DB_USER, DB_PASSWORD) or die ("MYSQL CONNECTION DETAILS WERE INCORRECT");
		mysql_select_db(DB_NAME, $db_one) or die("DATABASE WASNT ABLE TO CONNECT");
		
		$RUN_QUERY = str_replace("(PREFIX)",$this->DefaultPrefix($system,$db_prefix),$this->SQLQuery($system));
 
		$result = mysql_query($RUN_QUERY, $db_one);
		while ($row = mysql_fetch_array($result, MYSQL_BOTH)) {

			$db_two = mysql_connect(DB_HOST, DB_USER, DB_PASSWORD);
			mysql_select_db(DB_NAME, $db_two);
 

			if($this->Save($row)){
				$IMPORTCOUNTER++;
			}else{
				 
			}

		}
		
		return $IMPORTCOUNTER;
	
	
	}

	function DefaultPrefix($system, $override=""){	

		if($override !=""){ return $override; }
	
		switch($system){
		
			case "linkbidscript": { return ""; } break;
		
			case "edirectory": { return ""; } break;
 
			case "phplinkbid": { return "tbl"; } break;

			case "phpld": { return "PLD"; } break;
		
			case "esyndicate": { return "SELECT * FROM ME"; } break;
		}

	}
	
	function SQLQuery($system){
	
		switch($system){
		
			case "linkbidscript": { 
			
				return "SELECT 
				(PREFIX)main.title as title, 
				(PREFIX)main.descr2 as description, 
				(PREFIX)main.descr1 as excerpt, 
				(PREFIX)main.site as url, 				 
				(PREFIX)main.email as email, 
				(PREFIX)main.bid as bid,
				(PREFIX)categorylisting.categoryname as cat_name
				FROM (PREFIX)main
				INNER JOIN (PREFIX)categorylisting ON ( (PREFIX)categorylisting.catlistid = (PREFIX)main.maincategory )
				WHERE (PREFIX)main.title != ''"; 
			
			} break;
		
			case "edirectory": {
			
				return "SELECT
				(PREFIX)listing.title as title, 
				(PREFIX)listing.fulltext_search as description, 
				(PREFIX)listing.description as excerpt, 
				(PREFIX)listing.url as url, 
				(PREFIX)listing.address as address,
				(PREFIX)listing.zip_code as zip, 				
				(PREFIX)listing.email as email, 
				(PREFIX)listingcategory.title as cat_name
				FROM (PREFIX)listing 
				INNER JOIN (PREFIX)listingcategory ON ( (PREFIX)listing.cat_1_id = (PREFIX)listingcategory.id )
				WHERE (PREFIX)listing.title !=''";
			
			
			
			} break;

			case "phplinkbid": { 
			
				return "SELECT
				(PREFIX)links.link_title as title, 	
				(PREFIX)links.link_description as description,
				(PREFIX)links.link_description as excerpt,
				(PREFIX)links.link_url as url,  	
				(PREFIX)categories.cat_title as cat_name
				FROM `(PREFIX)links` 
				INNER JOIN (PREFIX)categories ON ( (PREFIX)links.category_id = (PREFIX)categories.category_id )
				WHERE (PREFIX)links.link_title != ''";			
			
			} break;
	
			case "phpld": { 

				return "SELECT 
				(PREFIX)LINK.TITLE as title, 
				(PREFIX)LINK.DESCRIPTION as description, 
				(PREFIX)LINK.DESCRIPTION as excerpt, 
				(PREFIX)LINK.URL as url, 
				(PREFIX)LINK.ADDRESS as address, 
				(PREFIX)LINK.CITY as city, 
				(PREFIX)LINK.STATE as state, 
				(PREFIX)LINK.ZIP as zip, 
				(PREFIX)LINK.OWNER_NAME as name, 
				(PREFIX)LINK.OWNER_EMAIL as email, 
				(PREFIX)CATEGORY.TITLE as cat_name
				FROM `(PREFIX)LINK` 
				INNER JOIN (PREFIX)CATEGORY ON ( (PREFIX)LINK.CATEGORY_ID = (PREFIX)CATEGORY.ID )
				WHERE (PREFIX)LINK.DESCRIPTION !='' AND (PREFIX)LINK.TITLE != ''
				"; 

			} break;
		
			case "esyndicate": { 
			
			return "SELECT			
			(PREFIX)listings.title,
			(PREFIX)listings.description,
			(PREFIX)listings.url,
			(PREFIX)listings.email,
			(PREFIX)categories.title as cat_name,			
			(PREFIX)accounts.username as name			
			FROM (PREFIX)listings
			LEFT JOIN (PREFIX)categories ON ( (PREFIX)listings.category_id =  (PREFIX)categories.id )
			LEFT JOIN (PREFIX)accounts ON ( (PREFIX)listings.account_id =  (PREFIX)accounts.id )
			WHERE (PREFIX)listings.title != ''"; 
			
			
			
			} break;
		}
	
	}

function Save($data){

	global $wpdb;  $catzID = 0;

	$key_array = array('title','description','excerpt','cat_name');

	if(isset($data['cat_name']) && strlen($data['cat_name']) > 2){
	 
	$catzID = wp_create_category1($data['cat_name']);
	
	//$args = array('cat_name' =>  $data['cat_name']); 
	//$catzID = wp_insert_term($data['cat_name'], 'category', $args);	
	 
	}

	//

	$my_post = array();
	$my_post['post_title'] 		= $data['title'];
	$my_post['post_content'] 	= $data['description'];
	$my_post['post_excerpt'] 	= $data['excerpt'];
	$my_post['post_author'] 	= 1;
	$my_post['post_status'] 	= "publish";	 
	$my_post['post_category'] 	= array($catzID);
	

	if(isset($data['tags'])){	 $my_post['tags_input'] 	= $data['tags'];	}
 	$POSTID = wp_insert_post( $my_post );	
 
	if(is_numeric($POSTID) && $POSTID != 0){

		foreach($data as $key=>$value){	
			if(!in_array($key,$key_array) && !is_numeric($key) ){		
				update_post_meta($POSTID,$key,$value);	
			}	 
		}

		return true;
	}else{
		return false;	
	}


}





}

?>