<?php

$state_included = array('Malaysia','Australia','Indonesia','India','Canada','United States','United States of America','China','France','Germany','United Kingdom','Spain','Scotland');

$state_scotland = array('Aberdeen City','Aberdeenshire','Angus','Argyll and Bute','City of Edinburgh','Clackmannanshire','Dumfries and Galloway','Dundee City','East Ayrshire','East Dunbartonshire','East Lothian','East Renfrewshire','Eilean Siar (Western Isles)','Falkirk','Fife','Glasgow City','Highland','Inverclyde','Midlothian','Moray','North Ayrshire','North Lanarkshire','Orkney Islands','Perth and Kinross','Renfrewshire','Shetland Islands','South Ayrshire','South Lanarkshire','Stirling','The Scottish Borders','West Dunbartonshire','West Lothian');

$state_uk = array('Barking and Dagenham','Barnet','Barnsley','Bath and North East Somerset','Bedfordshire','Bexley','Birmingham','Blackburn with Darwen','Blackpool','Bolton','Bournemouth','Bracknell Forest','Bradford','Brent','Brighton and Hove','Bromley','Buckinghamshire','Bury','Calderdale','Cambridgeshire','Camden','Cheshire','City of Bristol','City of Kingston upon Hull','City of London','Cornwall','Coventry','Croydon','Cumbria','Darlington','Derby','Derbyshire','Devon','Doncaster','Dorset','Dudley','Durham','Ealing','East Riding of Yorkshire','East Sussex','Enfield','Essex','Gateshead','Gloucestershire','Greenwich','Hackney','Halton','Hammersmith and Fulham','Hampshire','Haringey','Harrow','Hartlepool','Havering','Herefordshire','Hertfordshire','Hillingdon','Hounslow','Isle of Wight','Islington','Kensington and Chelsea','Kent','Kingston upon Thames','Kirklees','Knowsley','Lambeth','Lancashire','Leeds','Leicester','Leicestershire','Lewisham','Lincolnshire','Liverpool','Luton','Manchester','Medway','Merton','Middlesbrough','Milton Keynes','Newcastle upon Tyne','Newham','Norfolk','North East Lincolnshire','North Lincolnshire','North Somerset','North Tyneside','North Yorkshire','Northamptonshire','Northumberland','Nottingham','Nottinghamshire','Oldham','Oxfordshire','Peterborough','Plymouth','Poole','Portsmouth','Reading','Redbridge','Redcar and Cleveland','Richmond upon Thames','Rochdale','Rotherham','Rutland','Salford','Sandwell','Sefton','Sheffield','Shropshire','Slough','Solihull','Somerset','South Gloucestershire','South Tyneside','Southampton','Southend-on-Sea','Southwark','St. Helens','Staffordshire','Stockport','Stockton-on-Tees','Stoke-on-Trent','Suffolk','Sunderland','Surrey','Sutton','Swindon','Tameside','Telford and Wrekin','Thurrock','Torbay','Tower Hamlets','Trafford','Wakefield','Walsall','Waltham Forest','Wandsworth','Warrington','Warwickshire','West Berkshire','West Sussex','Westminster','Wigan','Wiltshire','Windsor and Maidenhead','Wirral','Wokingham','Wolverhampton','Worcestershire','York');

$state_germany = array('Baden-Wuerttemberg','Bayern','Berlin','Brandenburg','Bremen','Hamburg','Hessen','Mecklenburg-Vorpommern','Niedersachsen','Nordrhein-Westfalen','Rheinland-Pfalz','Saarland','Sachsen','Sachsen-Anhalt','Schleswig-Holstein','Thueringen');

$state_france = array('Alsace','Aquitaine','Auvergne','Basse-Normandie','Bourgogne','Bretagne','Centre','Champagne-Ardenne','Corse','Franche-Comte','Haute-Normandie','Ile-de-France','Languedoc-Roussillon','Limousin','Lorraine','Midi-Pyrenees','Nord-Pas-de-Calais','Pays de la Loire','Picardie','Poitou-Charentes','Provence-Alpes-Cote dAzur','Rhone-Alpes');

$state_china = array('Anhui','Beijing','Chongqing','Fujian','Gansu','Guangdong','Guangxi','Guizhou','Hainan','Hebei','Heilongjiang','Henan','Hubei','Hunan','Jiangsu','Jiangxi','Jilin','Liaoning','Nei Mongol','Ningxia','Qinghai','Shaanxi','Shandong','Shanghai','Shanxi','Sichuan','Tianjin','Xinjiang','Xizang (Tibet)','Yunnan','Zhejiang');

$state_usa = array('Alabama', 'Alaska','Arizona','Arkansas','California','Colorado','Connecticut','Delaware','District of Columbia','Florida','Georgia','Hawaii','Idaho','Illinois','Indiana','Iowa','Kansas','Kentucky','Louisiana','Maine','Maryland','Massachusetts','Michigan','Minnesota','Mississippi','Missouri','Montana','Nebraska','Nevada','New Hampshire','New Jersey','New Mexico','New York','North Carolina','North Dakota','Ohio','Oklahoma','Oregon','Pennsylvania','Rhode Island','South Carolina','South Dakota','Tennessee','Texas','Utah','Vermont','Virginia','Washington','West Virginia','Wisconsin','Wyoming');

$state_spain = array('Andalucia','Aragon','Asturias','Baleares (Balearic Islands)','Canarias (Canary Islands)','Cantabria','Castilla y Leon','Castilla-La Mancha','Cataluna','Ceuta','Communidad Valencian','Extremadura','Galicia','Islas Chafarinas','La Rioja','Madrid','Melilla','Murcia','Navarra','Pais Vasco (Basque Country)','Penon de Alhucemas','Penon de Velez de la Gomera');

$state_romania = array('Alba','Arad','Arges','Bacau','Bihor','Bistr ita-Nasaud','Botosani','Brasov','Braila','Bucuresti - Sector 1','Bucuresti - Sector 2','Bucuresti - Sector 3','Bucuresti - Sector 4','Bucuresti - Sector 5','Bucuresti - Sector 6','Buzau','Caras-Severin','Calarasi','Cluj','Constanta','Covasna',' Dambovita','Dolj','Galati','Giurgiu','Gorj','Hargh ita','Hunedoara','Ialomita','Iasi','Ilfov','Maramu res','Mehedinti','Mures','Neamt','Olt','Prahova',' Satu Mare','Salaj','Sibiu','Suceava','Teleorman','Timis ','Tulcea','Vaslui','Valcea','Vrancea');

$state_canada = array("Alberta","British Columbia","Manitoba","New Brunswick","Newfoundland and Labrador","Northwest Territries","Nova Scotia","Ontario","Prince Edward Island","Quebec","Saskatchewan","Yukon Territory");

$state_india = array("Andaman and Nicobar Islands","Andhra Pradesh","Arunachal Pradesh","Assam","Bengal","Bihar","Chandigarh","Chhattisgarh","Dadra and Nagar Haveli","Daman and Diu","Delhi","Goa","Gujarat","Haryana","Himachal Pradesh","Jharkhand","Karnataka","Kashmir","Kerala","Madhya Pradesh","Maharashtra","Manipur","Meghalaya","Mizoram","Nagaland","Orissa","Pondicherry","Punjab","Rajasthan","Sikkim","Tamil Nadu","Tripura","Uttar Pradesh","Uttarakhand");

$state_indonesia = array("Aceh","Bali","Bengkulu","Central Sulawesi","East Java","East Kalimantan","East Nusa Tenggara","Jakarta Raya","Jambi","Jawa Barat","Kalimantan Tengah","Lampung","Maluku ","North Sulawesi","North Sumatra","Nusa Tenggara Barat","Papua","Riau","South Kalimantan","South Sulawesi","South Sumatra","Sulawesi Barat","Sulawesi Tenggara","West Java","West Kalimantan","West Sumatra","Yogyakarta");

$state_australia = array("Australian Capital Territory","New South Wales","Northern Territory","Queensland","South Australia","Tasmania","Victoria","Western Australia");

$state_malaysia = array("Federal Territory of Labuan","Johor","Kedah","Kelantan","Kuala Lumpur","Melaka","Negeri Sembilan","Pahang","Perak","Perlis","Pulau Pinang","Putrajaya","Sabah","Sarawak","Selangor","Terengganu");

?>