<?php

/***************** DO NOT EDIT THIS FILE *************************
******************************************************************

INFORMATION:
------------

This is a core theme file, you should not need to edit 
this file directly. Code changes maybe lost during updates.

LAST UPDATED: June 26th 2011
EDITED BY: MARK FAIL
------------------------------------------------------------------

******************************************************************/

function _iscurlinstalled() {
	if  (in_array  ('curl', get_loaded_extensions())) {
		return true;
	}
	else{
		return false;
	}
}
 
if(function_exists("get_option")){  
	$i=0; $c=1;
	
	if (_iscurlinstalled()){}else{ die("cURL is NOT installed on your hosting account, please contact your hosting provider to enable this."); }
	
	$PageData = fetch_URL($_POST['domz_link']); 
	$PageData = StripHeaderFooter($PageData,'<fieldset class="fieldcap">','</fieldset>');

 
	foreach($PageData as $group){ 
		
	
		//$pos = strpos($group, '<li><a href="http'); 
		$pos1 = strpos($group, 'navigate');				
		$pos2 = strpos($group, 'See also');

		
		if ($pos1 !== false || $pos2 !== false) {   }else{
	 
		
		$gg = explode("</fieldset>",$group); 
		
		$group = $gg[0];
	
		$group = str_replace("<ul>","",str_replace("</ul>","",$group));	
		$links = explode("<li>",$group);			
		// die($group);
 
		foreach($links as $item){ if(strlen($item) > 5){ 
	
		$aa = explode("</a>",$item);
		$bb = explode('">',$aa[0]);
		$data['title'] = $bb[1];
	
		preg_match_all('<a href=\"(.*?)\">',$item, $ll);	
		$data['link'] = $ll[1][0];
	
		$data['description'] = strip_tags($item);
	
		if($data['title'] == ""){
			$data['title'] = $data['description'];
		}
	
				if(strlen(strip_tags($data['title'])) > 10 ){
				 
				  $my_post = array();
				  $my_post['post_title'] 	= strip_tags($data['title']);
				  $my_post['post_content'] 	= $data['description'];
				  $my_post['post_excerpt'] 	= $data['description'];
				  $my_post['post_status'] 	= "publish";
				  $my_post['post_author'] 	= $user_ID;
				  $my_post['post_category'] = $_POST['import']['cat'];
		
				  $POSTID = wp_insert_post( $my_post );		
			  
				  add_post_meta($POSTID,"url",$data['link']);
				  add_post_meta($POSTID,"hits","0");
		 		  add_post_meta($POSTID,"featured","no");
				$i++;
		
				}
	 
			} 
		  }
	
		}
	}

 



}
 
function StripHeaderFooter($data, $customHeader="", $customFooter=""){

$This = explode($customHeader,$data);

 
return $This;
 
}

?>